package com.module.hrm.web.common.enumeration;

public enum MessageKeys {
    NotNull("validation.notNull"),
    NotBlank("validation.notBlank"),
    NotEmpty("validation.notEmpty"),
    Min("validation.min"),
    Max("validation.max"),
    Size("validation.size"),
    ValidateString("validation.validateString"),
    Pattern("validation.pattern"),
    Email("validation.email"),
    EnumKeys("validation.enumKey"),
    DateFormat("validation.dateFormat"),
    DateTimeFormat("validation.dateTimeFormat"),
    DateIsPast("validation.dateIsPast"),
    DateIsFuture("validation.dateIsFuture"),
    TimeFormat("validation.timeFormat"),

    I_SUCCESS("info.success"),

    ERROR_TITLE("error.title"),
    ERROR_TITLE_2("error.title2"),

    ERROR_SYSTEM("error.system"),
    ERROR_WEB_CLIENT("error.webClient"),
    ERROR_ACCESS_DENIED("error.accessDenied"),
    ERROR_VALIDATION("error.validation"),
    ERROR_CONCURRENCY_FAILURE("error.concurrencyFailure"),
    ERROR_CODE_NOT_FOUND("error.codeNotfound"),
    ERROR_NOT_FOUND("error.notfound"),
    ERROR_IS_REQUIRED("error.isRequired"),
    //    ERROR_NOT_BELONG("error.notBelong"),

    ERROR_RESOURCE_EXISTED("error.resourceExisted"),
    ERROR_RESOURCE_IN_USED("error.resourceInUsed"),
    ERROR_RESOURCE_EXPIRED("error.resourceExpired"),
    ERROR_SORT_INVALID("error.sortInvalid"),
    ERROR_ID_INVALID("error.idInvalid"),

    ERROR_INACTIVATED("error.inactivated"),
    ERROR_DATE_RANGE("error.dateRange"),
    ERROR_DATE_RANGE_CONFLICT("error.dateRangeConflict"),
    ERROR_DATE_NOT_PAST("error.dateNotPast"),
    ERROR_DATE_MUST_BE_FUTURE("error.dateMustBeFuture"),
    ERROR_DATE_MUST_BE_TODAY("error.dateMustBeToday"),
    ERROR_DATE_MUST_BE_BEFORE("error.dateMustBeBefore"),
    ERROR_DATE_OVER_T_PLUS("error.dateOverTplus"),
    ERROR_MAX_RATE("error.maxRate"),

    ERROR_DATA_STATUS_ACTIVED("error.status.actived"),
    ERROR_DATA_STATUS_INCORRECT("error.status.incorrect"),
    ERROR_DATA_STATUS_INCORRECT_2("error.status.incorrect2"),
    ERROR_STATUS_INCORRECT("error.status.statusIncorrect"),
    ERROR_DATA_MUST_BE_STATUS("error.status.dataMustBe"),
    ERROR_DATA_NOT_CHANGE("error.data.notChange"),
    ERROR_DATA_SYNCED("error.data.isSynced"),
    ERROR_SYNCED_FAILURE("error.data.syncedFailure"),
    ERROR_SYNCED_FAILURE_DETAIL("error.data.syncedFailureDetail"),
    ERROR_DATA_CHANGED("error.data.lockingFailure"),
    ERROR_SALES_TEAM_INCORRECT("error.salesTeam.salesTeamIncorrect"),

    FILE_SIZE_LIMIT("error.file.sizeLimit"),
    FILE_NAME_LIMIT("error.file.nameLimit"),
    CONTTENT_TYPE_NOT_SUPPORT("error.file.contentTypeNotSupport"),
    FILE_PARSED_EXCEPTION("error.file.parsedException"),
    FILE_READ_EXCEPTION("error.file.readException"),
    FILE_WRITE_EXCEPTION("error.file.writeException"),
    FILE_UPLOAD_EXCEPTION("error.file.uploadException"),
    FILE_HEADER_INVALID("error.file.headerInvalid"),
    FILE_ROW_INVALID("error.file.rowInvalid"),
    FILE_ROW_WRONG_TYPE("error.file.rowWrongType"),
    FILE_CELL_INVALID("error.file.cellInvalid"),
    FILE_CELL_TYPE_INVALID("error.file.cellTypeInvalid"),
    FILE_DUPLICATED_KEY("error.file.duplicatedKey"),

    FILE_DATE_MUST_BE_FUTURE("error.file.dateMustBeFuture"),
    FILE_DATE_REQUIRED("error.file.dateRequired"),
    FILE_TIME_INVALID("error.file.timeInvalid"),

    CONNECTION_OPEN_EXCEPTION("error.connection.openException"),
    CONNECTION_INSERT_EXCEPTION("error.connection.insertException"),
    CONNECTION_CLOSE_EXCEPTION("error.connection.closeException"),
    DB_GENERATE_EXCEPTION("error.db.generateException"),
    DB_READ_EXCEPTION("error.db.readException"),

    LOGIN_FAILURE("error.loginFailure"),
    TOKEN_EXPIRED("error.tokenExpired"),

    PASSWORD_SAME_OLD("error.user.passwordSameOld"),
    PASSWORD_NOT_MATCH("error.user.passwordNotMatch"),
    USER_PASSWORD_NOT_CHANGE("error.user.passwordNotChange"),
    CURRENT_PASSWORD_INCORRECT("error.user.passwordIncorrect"),
    NEED_CHANGE_PASSWORD("error.user.needChangePassword"),

    LIST_EMPTY("error.list.empty"),
    LIST_MUST_ONE("error.list.mustOne"),
    LIST_SIZE_INVALID("error.list.sizeInvalid"),
    LIST_SIZE_OVER("error.list.sizeOver"),

    LEVEL_INDEX_INVALID("error.level.indexInvalid"),

    USER_IS_NOT_EXISTED("error.user.isNotExisted"),
    USER_IS_INACTIVATED("error.user.isInactivated"),
    USER_IS_EXPIRED("error.user.isExpired"),
    USER_IS_DELETED("error.user.isDeleted"),
    USER_NOT_UPDATE_STATUS("error.user.notUpdateStatus"),
    USER_KEY_ALREADY_EXISTS("error.user.keyExisted"),

    CUSTOMER_HAS_NO_ADDRESS("error.customer.addressNotExisted"),
    CUSTOMER_STATUS_IS_APPROVAL("error.customer.statusIsApproval"),
    CUSTOMER_STATUS_IS_CONFIRMED("error.customer.statusIsConfirmed"),
    CUSTOMER_ROUTE_IS_BLANK("error.customer.routeIsBlank"),
    CUSTOMER_ROUTE_IS_DUPLICATE("error.customer.customerDuplicateOnRoute"),
    CUSTOMER_ROUTE_INVALID("error.customer.customerRouteInvalid"),
    CUSTOMER_SALES_OUT_IS_PROCESSING("error.customer.salesOutStillProcessing"),
    CUSTOMER_LOYALTY_IS_UNPAID("error.customer.loyaltyIsUnpaid"),
    CUSTOMER_MUST_HAVE_ORDER("error.customer.mustHaveOrder"),

    CUSTOMER_IDENTIFY_INVALID("error.customer.invalidIdentify"),
    CUSTOMER_MCP_NOT_FOUND_ON_ROUTE("error.customer.mcpNotFoundOnRoute"),
    CUSTOMER_MCP_MODIFY_INCORRECT("error.customer.mcpModifyIncorrect"),
    CUSTOMER_IN_ROUTE("error.customer.customerInRoute"),

    DISTRIBUTOR_PROVINCE_NOT_SAME("errror.distributor.provinceNotSame"),
    DISTRIBUTOR_REGION_NOT_IN_LOCATED("errror.distributor.regionNotInLocated"),
    DISTRIBUTOR_SHIP_TO_REQUIRED("error.distributor.shipToIsRequired"),

    USER_IMPORT_RSM_USM("error.user.importRsmOrUsm"),
    USER_NOT_SD_RSM("error.user.isNotSdRsm"),
    USER_NOT_USM("error.user.isNotUsm"),
    USER_NOT_SD("error.user.isNotSd"),
    USER_NOT_SALES_MAN("error.user.isNotSalesMan"),
    //ROUTE_DETAIL_IS_INVALID("error.route.detailIsInvalid"),
    ROUTE_DETAIL_NOT_SETUP("error.route.detailNotSetup"),
    ROUTE_EXIST_DETAIL("error.route.salesRouteExistDetails"),
    USER_NOT_SALES_OPERATION("error.user.isNotSalesOp"),

    // Group
    GROUP_CODE_DUPLICATED("error.group.codeDuplicated"),

    SALES_MAN_IS_ASSIGNED("error.route.salesManAssigned"),

    SR_MODIFY_IS_ACTIVE_USER("error.route.isActiveUser"),
    SR_DISTRIBUTION_NOT_SAME("error.route.invalidDistributionChannel"),

    SF_POSTION_IS_USM("error.salesForce.positionIsUsm"),
    SF_USM_POSITION_INVALID("error.salesForce.usmPositionInvalid"),
    SF_MODIFY_IS_ACTIVE_USER("error.salesForce.isActiveUser"),
    SF_HIERARCHY_NOT_SETUP("error.salesForce.hierarchyNotSetup"),
    SF_HIERARCHY_NOT_SETUP_2("error.salesForce.hierarchyNotSetup2"),
    SF_HIERARCHY_UPDATE_SAME_LEVEL("error.salesForce.hierarchyUpdateSameLevel"),
    SF_HIERARCHY_HAS_USER("error.salesForce.hierarchyHasUser"),
    SF_HIERARCHY_HAS_DISTRIBUTOR("error.salesForce.hierarchyHasDistributor"),
    SF_HIERARCHY_USER_ASSIGNED("error.salesForce.userIsAssigned"),
    SF_HIERARCHY_DISTRIBUTOR_ASSIGNED("error.salesForce.distributorIsAssigned"),
    SF_HIERARCHY_DISTRIBUTOR_NOT_ASSIGNED("error.salesForce.distributorIsNotAssigned"),

    VISIT_PLAN_WEEK_NO_INCORRECT("error.visitPlan.weekNoIncorrect"),
    VISIT_PLAN_FROM_DATE_MUST_BE_FUTURE("error.visitPlan.fromDateMustBeFuture"),
    //VISIT_PLAN_DISTRIBUTOR_CODE_NOT_EXIST("error.visitPlan.distributorCodeNotExist"),
    //VISIT_PLAN_CUSTOMER_CODE_NOT_EXIST("error.visitPlan.customerCodeNotExist"),
    //VISIT_PLAN_CUSTOMER_NOT_APPROVAL_OR_INACTIVATED("error.visitPlan.customerNotApprovalOrInactivated"),
    VISIT_PLAN_WARNING_CHANGE_D_FLAG("error.visitPlan.warningChangeDFlag"),
    VISIT_PLAN_WARNING_CHANGE_WEEK_NO("error.visitPlan.warningChangeWeekNo"),
    VISIT_PLAN_WARNING_INACTIVE("error.visitPlan.warningInactive"),
    VISIT_PLAN_WARNING_SETTING_ROUTE_AND_INACTIVE("error.visitPlan.warningSettingRouteAndInactive"),
    VISIT_PLAN_WARNING_SETTING_ROUTE("error.visitPlan.warningSettingRoute"),
    VISIT_PLAN_TP_AND_NGK_OFF_WARNING_CHANGE_D_FLAG("error.visitPlan.warningThAndNgkOffChangeDFlag"),
    VISIT_PLAN_TP_AND_NGK_OFF_WARNING_CHANGE_WEEK_NO("error.visitPlan.warningThAndNgkOffChangeWeekNo"),
    VISIT_PLAN_TP_AND_NGK_OFF_WARNING_INACTIVE("error.visitPlan.warningThAndNgkOffInactive"),
    VISIT_PLAN_CREATE_OFF_CUL_OR_OFF_BEV_WITH_OTHER_SALES_TEAM("error.visitPlan.createOffCulOrOffBevWithOtherSalesTeam"),
    VISIT_PLAN_CREATE_WITH_OTHER_SALES_TEAM("error.visitPlan.createWithOtherSalesTeam"),

    VISIT_PLAN_ONLY_ONE_DAY("error.visitPlan.onlyOneDay"),
    VISIT_PLAN_MUST_FUTURE("error.visitPlan.mustFuture"),
    VISIT_PLAN_MUST_CURRENT("error.visitPlan.mustCurrent"),
    VISIT_PLAN_DAY_INVALID("error.visitPlan.dayInvalid"),
    VISIT_PLAN_DAY_REQUIRED("error.visitPlan.dayRequired"),

    SEQUENCE_IS_INVALID("error.sequence.isInvalid"),

    INVENTORY_QTY_NOT_CHANGED("error.inventory.qtyNotChanged"),
    INVENTORY_QTY_NOT_MATCH("error.inventory.qtyNotMatch"),
    INVENTORY_QTY_GREATER_0("error.inventory.qtyGreaterZero"),
    INVENTORY_CHECK_EXISTED("error.inventory.checkExisted"),
    INVENTORY_OUT_OF_STOCK("error.inventory.outOfStock"),
    INVENTORY_VALID_AMOUNT("error.inventory.validAmount"),
    INVENTORY_UPLOAD_DISTRIBUTOR_NOT_MAPPING("error.inventory.distributorNotMapping"),

    PRODUCT_CODE_DUPLICATED("error.product.codeDuplicated"),
    CATALOG_CODE_DUPLICATED("error.catalog.codeDuplicated"),
    CODE_DUPLICATED("error.code.duplicated"),

    CATALOG_CODE_BEING_USED("error.catalog.codeBeingUsed"),

    SALES_ORDER_FROM_MOBILE("error.order.fromMobile"),
    SALES_ORDER_IN_DELIVERY("error.order.inDelivery"),
    SALES_ORDER_CUSTOMER_CANNOT_CHANGE("error.order.customerNotChange"),
    SALES_ORDER_QTY_GREATER_0("error.order.qtyGreaterZero"),
    SALES_ORDER_TOTAL_QTY_GREATER_05("error.order.totalQtyGreater05"),
    SALES_ORDER_TOTAL_AMOUNT_GREATER_0("error.order.totalAmountGreaterZero"),
    SALES_ORDER_IS_RETURNED("error.order.isReturned"),
    SALES_ORDER_IS_CLAIMED("error.order.isClaimed"),
    SALES_ORDER_COUPON_IS_USED("error.order.couponIsUsed"),
    SALES_ORDER_PROMOTION_CAL_REQUIRED("error.order.promotionCalRequired"),
    SALES_ORDER_PROMOTION_CAL_IS_USED("error.order.promotionCalIsUsed"),
    SALES_ORDER_SAME_IS_INVALID("error.order.sameDayIsInvalid"),
    SALES_ORDER_LUCKY_NOT_CLAIMED("error.order.luckyNotClaimed"),

    DELIVERY_ORDER_DATE_MUST_SAME("error.delivery.orderDateMustSame"),

    LOYALTY_ONLY_CHANGE_TO_DATE("error.loyalty.toDateOnlyChange"),
    LOYALTY_DATE_IS_PAST("error.loyalty.dateIsPast"),
    LOYALTY_PREPARE_TO_PAY("error.loyalty.prepareToPay"),
    LOYALTY_LEVEL_TOP_IS_REQUIRED("error.loyalty.loyaltyTopIsRequired"),
    LOYALTY_PAID_FROM_DATE_GREATER_T_PLUS_DAY("error.loyalty.paidFromDateGreaterTDay"),
    LOYALTY_NET_AMOUNT_INCORRECT("error.loyalty.netAmountIncorrect"),

    //PROMOTION_ONLY_CHANGE_TO_DATE("error.promotion.toDateOnlyChange"),
    PROMOTION_DATE_IS_PAST("error.promotion.dateIsPast"),
    PROMOTION_ORDER_DUPLICATED("error.promotion.orderDuplicated"),
    PROMOTION_MIN_ONLY_2_CONDITION("error.promotion.minOnly2Conditions"),
    PROMOTION_MIN_ONLY_NOT_OR("error.promotion.minOnlyNotOr"),
    PROMOTION_LEVEL_TOP_IS_REQUIRED("error.promotion.promotionTopIsRequired"),
    PROMOTION_PURCHASE_CONDITION_ONLY_SKU("error.promotion.purchaseConditionOnlySku"),

    PROGRAM_HAS_IO("error.program.hasIo"),
    PROGRAM_PROPOSAL_MOIT_REQUIRED("error.program.proposalMoitRequired"),

    MOBILE_LOGIN_INCORRECT("error.mobile.loginIncorrect"),
    MOBILE_VERSION_INCORRECT("error.mobile.versionIncorrect"),
    MOBILE_TIME_INCORRECT("error.mobile.timeIncorrect"),
    MOBILE_GPS_INCORRECT("error.mobile.gpsIncorrect"),
    MOBILE_DEVICE_NOT_FOUND("error.mobile.deviceNotFound"),
    MOBILE_DISTRIBUTOR_NOT_SETUP("error.mobile.distributorNotSetup"),
    MOBILE_SALES_ROUTE_NOT_SETUP("error.mobile.salesRouteNotSetup"),
    //MOBILE_CUSTOMER_PROVINCE_INCORRECT("error.mobile.provinceIncorrect"),
    MOBILE_CARE_TYPE_CLOSED("error.mobile.careTypeBeClosed"),
    MOBILE_CARE_TYPE_NOT_CLOSED("error.mobile.careTypeBeNotClosed"),
    MOBILE_DISTANCE_INVALID("error.mobile.distanceInvalid"),

    ACCOUNT_NOT_ONE_DEVICE("error.mobile.accountNotOneDevice"),
    DEVICE_NOT_ONE_ACCOUNT("error.mobile.deviceNotOneAccount"),

    ERROR_DATA_TYPE_INCORRECT("error.type.incorrect"),
    // Apply Region
    APPLY_REGION_TERRITORY_LIST_EMPTY("applyRegion.territory.empty"),

    // Region
    REGION_CODE_DUPLICATED("error.region.codeDuplicated"),

    // Upload DisplayEntry
    DISPLAY_ENTRY_INVALID_UOM("error.displayEntry.invalidUom"),
    DISPLAY_ENTRY_INVALID_QTY("error.displayEntry.invalidQty"),
    DISPLAY_ENTRY_INVALID_NOT_ORDER_TYPE("error.displayEntry.notOrderType"),
    DISPLAY_ENTRY_INVALID_INVALID_NUM_RECORD("error.displayEntry.invalidNumRecord"),
    DISPLAY_ENTRY_INVALID_INVALID_NUM_RECORD_2("error.displayEntry.invalidNumRecord2"),

    // Upload Si-targets
    UPLOAD_COLUMN_INVALID("error.column.invalid"),
    UPLOAD_SUPERMARKET_NONEMATCH("error.supermarketCode.noneMatch"),
    UPLOAD_TOTAL_AMOUNT_INVALID("error.siTarget.totalAmountInvalid"),

    BARCODE_PRODUCT_INVALID("error.barcodeProduct.invalid"),

    // Upload file
    UPLOAD_FILE_SUCCESSFUL("file.upload.successful"),

    // NOTIFICATION
    NOTIFICATION_IMAGE_BOTTOM_INVALID("error.notification.imageBottom"),
    NOTIFICATION_IMAGE_TOP_INVALID("error.notification.imageTop"),
    NOTIFICATION_ZALO_TOKEN_SIGNATURE_INVALID("error.notification.zalo.token.signature_invalid"),
    NOTIFICATION_ZALO_TOKEN_EXPIRE("error.notification.zalo.token.expire"),
    NOTIFICATION_ZALO_TOKEN_INVALID("error.notification.zalo.token.invalid"),
    NOTIFICATION_ZALO_TOKEN_USED("error.notification.zalo.token.used"),
    NOTIFICATION_ZALO_PHONE_INVALID("error.notification.zalo.phone_invalid"),
    NOTIFICATION_ZALO_OA_SHARE_INFO_TEXT("zalo.oa.share_info.text"),
    NOTIFICATION_ZALO_OA_SHARE_INFO_TITLE("zalo.oa.share_info.title"),

    COACHING_IN_PAST("error.coaching.inPast"),
    COACHING_MUST_BE_WW("error.coaching.mustBeWorkwith"),
    COACHING_VISIT_NOT_UPDATE("error.coaching.visitNotUpdate"),
    COACHING_WW_EXIST("error.coaching.wwIsExisted"),
    COACHING_WW_COUNT_INVALID("error.coaching.wwCountInvalid"),
    COACHING_NWW_IN_MONTH_OVER("error.coaching.nWWInMonthOver"),
    //COACHING_TIME_IS_VALID("error.coaching.timeIsValid"),
    //COACHING_MINUTE_IS_VALID("error.coaching.minuteIsValid"),
    //COACHING_END_TIME_BEFORE_START_TIME("error.coaching.endTimeBeforeStartTime"),
    COACHING_NOT_FOUND("error.coaching.notfound"),

    // sales target
    SALES_TARGET_CYCLE_NOT_FUTURE("error.salesTarget.notFuture"),
    SALES_TARGET_REQUIRED("error.salesTarget.requiredField"),
    SALES_TARGET_ZERO_AMOUNT("error.salesTarget.zeroAmount"),
    SALES_TARGET_NOT_SETUP("error.salesTarget.notSetup"),

    // target percentile
    TARGET_PERCENTILE_IS_NOT_PAST("error.targetPercentile.notPastMonth"),

    // target aso
    TARGET_ASO_IS_NOT_PAST("error.targetAso.notPastMonth"),

    // Van sales
    VAN_SALES_UNASSIGNED_ROUTE("error.vansales.routeUnassigned"),
    VAN_SALES_ASSIGNED_TRUCK("error.vansales.assignedTruck"),
    VAN_SALES_ASSIGNED_ROUTE("error.vansales.assignedUser"),
    VAN_SALES_EXIST_NOTE("error.vansales.existNote"),
    VAN_SALES_IN_PAST("error.vansales.inPast"),
    VAN_SALES_ASSIGNED_USER_INCORRECT("error.vansales.assignedUserIncorrect"),

    // Van sales note
    VAN_SALES_NOTE_IN_PAST("error.vansalesNote.inPast"),
    VAN_SALES_NOTE_ONLY_TODAY("error.vansalesNote.onlyToday"),

    VAN_SALES_SETTLEMENT_ANOTHER_DAY("error.vansalesSettlement.anotherDay"),
    VAN_SALES_SETTLEMENT_UNRECORDED("error.vansalesSettlement.notRecorded"),

    // Sampling Note
    SAMPLING_NOTE_IN_PAST("error.samplingNote.inPast"),
    SAMPLING_NOTE_ONLY_TODAY("error.samplingNote.onlyToday"),
    SAMPLING_NOTE_SALES_TEAM_INCORRECT("error.samplingNote.salesTeamIncorrect"),
    SAMPLING_NOTE_ALLOCATION_QTY_NOT_ENOUGH("error.samplingNote.allocationQtyNotEnough"),

    // Sampling Settlement
    SAMPLING_SETTLEMENT_ANOTHER_DAY("error.samplingSettlement.anotherDay"),
    SAMPLING_SETTLEMENT_UNRECORDED("error.samplingSettlement.notRecorded"),

    // Sampling Allocation
    ALLOCATION_SAMPLING_QTY_MUST_GREATER_SAMPLED_QTY("error.allocationSampling.samplingQtyMustGreaterThanSampledQty"),

    // Field Work
    FIELDWORK_DATA_IS_REQUIRED("error.fieldWork.dataIsRequired"),

    Z_RETAILER_ZALO_PROFILE_ID_INVALID("error.zRetailer.zaloProfileIdInvalid"),
    Z_RETAILER_ZALO_WEB_CLIENT("error.zRetailer.zaloWebClient"),
    Z_RETAILER_TOKEN_INVALID("error.zRetailer.tokenInValid"),
    Z_RETAILER_TOKEN_CUSTOMER_INVALID("error.zRetailer.tokenCustomerInValid"),
    Z_RETAILER_CUSTOMER_HAS_ZALO_MAPPING("error.zRetailer.customerHasZaloMapping"),
    Z_RETAILER_ZALO_PROFILE_NOT_FOUND("error.zRetailer.profileNotFound"),
    Z_RETAILER_ZALO_LOCATION_NOT_FOUND("error.zRetailer.locationNotFound"),
    Z_RETAILER_ZALO_PHONE_NOT_FOUND("error.zRetailer.phoneNotFound"),

    // Lucky Draw

    LUCKY_DRAW_OPTION_PERCENTAGE_MAX("error.luckyDrawOption.percentageMax"),
    LUCKY_DRAW_OPTION_PERCENTAGE_REWARD_QTY_INVALID("error.luckyDrawOption.qtyInvalid"),
    LUCKY_DRAW_REWARD_CANNOT_DELETE("error.luckyDrawOption.canNotDelete"),

    // Claim program
    CLAIM_PROGRAM_DISTRIBUTOR_NOT_BELONG_APPLY("error.claimProgram.distributorNotBelongApply"),

    // Payment note
    EXPENSE_WITHIN_PAYMENT_NOTE("error.paymentNote.expenseWithinNote"),

    DISTRIBUTOR_NOT_SETUP_SHIPTO("error.distributor.shiptoNotSetup"),

    // Daily SalesOut
    EXCEL_COMMON_TABLE_NO("pdf.common.table.no"),
    DAILY_SALES_OUT_TITLE("pdf.dailySalesOut.title"),
    DAILY_SALES_OUT_PRINT_DATE("pdf.dailySalesOut.printDate"),
    DAILY_SALES_OUT_FROM_DATE("pdf.dailySalesOut.fromDate"),
    DAILY_SALES_OUT_TO_DATE("pdf.dailySalesOut.toDate"),
    DAILY_SALES_OUT_DETAIL_ROUTE_CODE("pdf.dailySalesOut.table.routeCode"),
    DAILY_SALES_OUT_DETAIL_SALES_NAME("pdf.dailySalesOut.table.salesName"),
    DAILY_SALES_OUT_DETAIL_SALES_DATE("pdf.dailySalesOut.table.salesDate"),
    DAILY_SALES_OUT_DETAIL_ORDER_DISCOUNT_PROMOTION_DISCOUNT_AMOUNT("pdf.dailySalesOut.table.orderDiscountPromotionDiscountAmount"),
    DAILY_SALES_OUT_DETAIL_DISCOUNT_LOYALTY_DISCOUNT_AMOUNT("pdf.dailySalesOut.table.discountLoyaltyDiscountAmount"),
    DAILY_SALES_OUT_DETAIL_PROMOTION("pdf.dailySalesOut.table.promotion"),
    DAILY_SALES_OUT_DETAIL_REWARD("pdf.dailySalesOut.table.reward"),
    DAILY_SALES_OUT_DETAIL_BEFORE_CK("pdf.dailySalesOut.table.beforeCK"),
    DAILY_SALES_OUT_DETAIL_AFTER_CK("pdf.dailySalesOut.table.afterCK"),
    DAILY_SALES_OUT_DETAIL_TOTAL("pdf.dailySalesOut.table.total"),
    DAILY_SALES_OUT_DETAIL_TOTAL_BY("pdf.dailySalesOut.table.totalBy"),

    // SalesOutByRoute
    SALES_OUT_BY_ROUTE_TITLE("pdf.salesRoute.title"),
    SALES_OUT_BY_ROUTE_DISTRIBUTOR_TITLE("pdf.salesRoute.distributor.title"),
    SALES_OUT_BY_ROUTE_PRINT_DATE("pdf.salesRoute.printDate"),
    SALES_OUT_BY_ROUTE_FROM_DATE("pdf.salesRoute.fromDate"),
    SALES_OUT_BY_ROUTE_TO_DATE("pdf.salesRoute.toDate"),
    SALES_OUT_BY_ROUTE_ROUTE_CODE("pdf.salesRoute.routeCode"),
    SALES_OUT_BY_ROUTE_SALES_NAME("pdf.salesRoute.salesName"),
    SALES_OUT_BY_ROUTE_DETAIL_PRODUCT_CODE("pdf.salesRoute.table.product.productCode"),
    SALES_OUT_BY_ROUTE_DETAIL_PRODUCT_NAME("pdf.salesRoute.table.product.productName"),
    SALES_OUT_BY_ROUTE_DETAIL_SALES_UOM_CODE("pdf.salesRoute.table.product.salesUomCode"),
    SALES_OUT_BY_ROUTE_DETAIL_SECOND_SALES_UOM_CODE("pdf.salesRoute.table.product.secondSalesUomCode"),
    SALES_OUT_BY_ROUTE_DETAIL_QTY("pdf.salesRoute.table.product.qty"),
    SALES_OUT_BY_ROUTE_DETAIL_QTY1("pdf.salesRoute.table.product.qty1"),
    SALES_OUT_BY_ROUTE_DETAIL_QTY2("pdf.salesRoute.table.product.qty2"),
    SALES_OUT_BY_ROUTE_DETAIL_TOTAL_WEIGHT("pdf.salesRoute.table.product.weight"),
    SALES_OUT_BY_ROUTE_DETAIL_BEFORE_CK("pdf.salesRoute.table.product.beforeCK"),
    SALES_OUT_BY_ROUTE_DETAIL_AFTER_CK("pdf.salesRoute.table.product.afterCK"),
    SALES_OUT_BY_ROUTE_DETAIL_PROMOTION("pdf.salesRoute.table.product.promotion"),
    SALES_OUT_BY_ROUTE_DETAIL_LOYALTY("pdf.salesRoute.table.product.loyalty"),
    SALES_OUT_BY_ROUTE_DETAIL_DISCOUNT("pdf.salesRoute.table.product.discount"),
    SALES_OUT_BY_ROUTE_DETAIL_TOTAL("pdf.salesRoute.table.product.total"),
    SALES_OUT_BY_ROUTE_TOTAL_QTY("pdf.salesRoute.totalQty"),
    SALES_OUT_BY_ROUTE_TOTAL_ORDER("pdf.salesRoute.totalOrder"),
    SALES_OUT_BY_ROUTE_SKU_NO("pdf.salesRoute.SKUNo"),
    SALES_OUT_BY_ROUTE_TOTAL_DISCOUNT_PROMOTION("pdf.salesRoute.totalDiscountPromotion"),
    SALES_OUT_BY_ROUTE_TOTAL_DISCOUNT_LOYALTY("pdf.salesRoute.totalDiscountLoyalty"),

    // purchaseInvoiceDetail
    PURCHASE_INVOICE_DETAIL_TITLE("pdf.purchaseInvoiceDetail.title"),
    PURCHASE_INVOICE_DETAIL_PRINT_DATE("pdf.purchaseInvoiceDetail.printDate"),
    PURCHASE_INVOICE_DETAIL_FROM_DATE("pdf.purchaseInvoiceDetail.fromDate"),
    PURCHASE_INVOICE_DETAIL_TO_DATE("pdf.purchaseInvoiceDetail.toDate"),
    PURCHASE_INVOICE_DETAIL_VENDOR("pdf.purchaseInvoiceDetail.supplierName"),
    PURCHASE_INVOICE_DETAIL_PURCHASE_CODE("pdf.purchaseInvoiceDetail.table.col2"),
    PURCHASE_INVOICE_DETAIL_RECORD_DATE("pdf.purchaseInvoiceDetail.table.col3"),
    PURCHASE_INVOICE_DETAIL_SAP_PURCHASE_CODE("pdf.purchaseInvoiceDetail.table.col4"),
    PURCHASE_INVOICE_DETAIL_INVOICE_DATE("pdf.purchaseInvoiceDetail.table.col5"),
    PURCHASE_INVOICE_DETAIL_PRODUCT_CODE("pdf.purchaseInvoiceDetail.table.col6"),
    PURCHASE_INVOICE_DETAIL_PRODUCT_ABBR("pdf.purchaseInvoiceDetail.table.col7"),
    PURCHASE_INVOICE_DETAIL_SALES_UOM_CODE("pdf.purchaseInvoiceDetail.table.col8"),
    PURCHASE_INVOICE_DETAIL_KM_POSM("pdf.purchaseInvoiceDetail.table.col9"),
    PURCHASE_INVOICE_DETAIL_QTY("pdf.purchaseInvoiceDetail.table.col10"),
    PURCHASE_INVOICE_DETAIL_SALES_IN_PRICE("pdf.purchaseInvoiceDetail.table.col11"),
    PURCHASE_INVOICE_DETAIL_DISCOUNT("pdf.purchaseInvoiceDetail.table.col12"),
    PURCHASE_INVOICE_DETAIL_NET_AMOUTN("pdf.purchaseInvoiceDetail.table.col13"),
    PURCHASE_INVOICE_DETAIL_TOTAL_AMOUNT("pdf.purchaseInvoiceDetail.table.col14"),
    PURCHASE_INVOICE_DETAIL_TOTAL("pdf.purchaseInvoiceDetail.table.total"),

    // Input-Output-Inventory
    INVENTORY_IN_OUT_TITLE("pdf.inOutInventory.title"),
    INVENTORY_IN_OUT_PRINT_DATE("pdf.inOutInventory.printDate"),
    INVENTORY_IN_OUT_FROM_DATE("pdf.inOutInventory.fromDate"),
    INVENTORY_IN_OUT_TO_DATE("pdf.inOutInventory.toDate"),
    INVENTORY_IN_OUT_DETAIL_PRODUCT_CODE("pdf.inOutInventory.table.productCode"),
    INVENTORY_IN_OUT_DETAIL_PRODUCT_NAME("pdf.inOutInventory.table.productName"),
    INVENTORY_IN_OUT_DETAIL_SALES_IN_PRINCE("pdf.inOutInventory.table.salesInPrice"),
    INVENTORY_IN_OUT_DETAIL_SALES_UOM_CODE("pdf.inOutInventory.table.salesUomCode"),
    INVENTORY_IN_OUT_DETAIL_SECOND_SALES_UOM_CODE("pdf.inOutInventory.table.secondSalesUomCode"),
    INVENTORY_IN_OUT_DETAIL_OPENING_STOCK("pdf.inOutInventory.table.openingStock"),
    INVENTORY_IN_OUT_DETAIL_INPUT("pdf.inOutInventory.table.input"),
    INVENTORY_IN_OUT_DETAIL_OUTPUT("pdf.inOutInventory.table.output"),
    INVENTORY_IN_OUT_DETAIL_STOCK_AVAIABLE("pdf.inOutInventory.table.stockAvailable"),
    INVENTORY_IN_OUT_DETAIL_NOT_IN_STOCK("pdf.inOutInventory.table.notInStock"),
    INVENTORY_IN_OUT_DETAIL_EST_STOCK("pdf.inOutInventory.table.estStock"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY("pdf.inOutInventory.table.input.buy"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK("pdf.inOutInventory.table.input.sendback"),
    INVENTORY_IN_OUT_DETAIL_IN_INCREASE("pdf.inOutInventory.table.input.increase"),
    INVENTORY_IN_OUT_DETAIL_IN_OTHER_INPUT("pdf.inOutInventory.table.input.otherInput"),
    INVENTORY_IN_OUT_DETAIL_IN_VANSALES_INPUT("pdf.inOutInventory.table.input.vanSalesInput"),
    INVENTORY_IN_OUT_DETAIL_IN_SAMPLING_INPUT("pdf.inOutInventory.table.input.samplingInput"),
    INVENTORY_IN_OUT_DETAIL_IN_TOTAL_INPUT("pdf.inOutInventory.table.input.totalInput"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES("pdf.inOutInventory.table.output.sales"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN("pdf.inOutInventory.table.output.sales.returnSupplier"),
    INVENTORY_IN_OUT_DETAIL_OUT_OTHER("pdf.inOutInventory.table.output.otherOutput"),
    INVENTORY_IN_OUT_DETAIL_OUT_DECREASE("pdf.inOutInventory.table.output.decrease"),
    INVENTORY_IN_OUT_DETAIL_OUT_VANSALES("pdf.inOutInventory.table.output.vanSalesOutput"),
    INVENTORY_IN_OUT_DETAIL_OUT_SAMPLING("pdf.inOutInventory.table.output.samplingOutput"),
    INVENTORY_IN_OUT_DETAIL_OUT_TOTAL("pdf.inOutInventory.table.output.total"),
    INVENTORY_IN_OUT_DETAIL_OPENING_STOCK_QTY("pdf.inOutInventory.table.openingStock.qty"),
    INVENTORY_IN_OUT_DETAIL_OPENING_STOCK_VALUE("pdf.inOutInventory.table.openingStock.value"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_BUY("pdf.inOutInventory.table.input.buy.buy"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_PROMOTION("pdf.inOutInventory.table.input.buy.promotion"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_TOTAL("pdf.inOutInventory.table.input.buy.total"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_QTY("pdf.inOutInventory.table.input.sendback.qty"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_PROMOTION("pdf.inOutInventory.table.input.sendback.promotion"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_TOTAL("pdf.inOutInventory.table.input.sendback.total"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_SELL("pdf.inOutInventory.table.output.sales.sell"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_PROMOTION("pdf.inOutInventory.table.output.sales.promotion"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_WAITING("pdf.inOutInventory.table.output.sales.waiting"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_TOTAL("pdf.inOutInventory.table.output.sales.total"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_QTY("pdf.inOutInventory.table.output.sales.returnSupplier.qty"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_PROMOTION("pdf.inOutInventory.table.output.sales.returnSupplier.promotion"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_TOTAL("pdf.inOutInventory.table.output.sales.returnSupplier.total"),
    INVENTORY_IN_OUT_DETAIL_OPENING_STOCK_QTY_UNIT1("pdf.inOutInventory.table.openingStock.qty.unit1"),
    INVENTORY_IN_OUT_DETAIL_OPENING_STOCK_QTY_UNIT2("pdf.inOutInventory.table.openingStock.qty.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_BUY_UNIT1("pdf.inOutInventory.table.input.buy.buy.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_BUY_UNIT2("pdf.inOutInventory.table.input.buy.buy.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_PROMOTION_UNIT1("pdf.inOutInventory.table.input.buy.promotion.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_PROMOTION_UNIT2("pdf.inOutInventory.table.input.buy.promotion.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_TOTAL_UNIT1("pdf.inOutInventory.table.input.buy.total.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_BUY_TOTAL_UNIT2("pdf.inOutInventory.table.input.buy.total.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_QTY_UNIT1("pdf.inOutInventory.table.input.sendback.qty.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_QTY_UNIT2("pdf.inOutInventory.table.input.sendback.qty.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_PROMOTION_UNIT1("pdf.inOutInventory.table.input.sendback.promotion.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_PROMOTION_UNIT2("pdf.inOutInventory.table.input.sendback.promotion.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_TOTAL_UNIT1("pdf.inOutInventory.table.input.sendback.total.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_SENDBACK_TOTAL_UNIT2("pdf.inOutInventory.table.input.sendback.total.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_INCREASE_UNIT1("pdf.inOutInventory.table.input.increase.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_INCREASE_UNIT2("pdf.inOutInventory.table.input.increase.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_OTHER_UNIT1("pdf.inOutInventory.table.input.otherInput.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_OTHER_UNIT2("pdf.inOutInventory.table.input.otherInput.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_VANSALES_UNIT1("pdf.inOutInventory.table.input.vanSalesInput.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_VANSALES_UNIT2("pdf.inOutInventory.table.input.vanSalesInput.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_SAMPLING_UNIT1("pdf.inOutInventory.table.input.samplingInput.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_SAMPLING_UNIT2("pdf.inOutInventory.table.input.samplingInput.unit2"),
    INVENTORY_IN_OUT_DETAIL_IN_TOTAL_INPUT_UNIT1("pdf.inOutInventory.table.input.totalInput.unit1"),
    INVENTORY_IN_OUT_DETAIL_IN_TOTAL_INPUT_UNIT2("pdf.inOutInventory.table.input.totalInput.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_SELL_UNIT1("pdf.inOutInventory.table.output.sales.sell.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_SELL_UNIT2("pdf.inOutInventory.table.output.sales.sell.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_PROMOTION_UNIT1("pdf.inOutInventory.table.output.sales.promotion.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_PROMOTION_UNIT2("pdf.inOutInventory.table.output.sales.promotion.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_WAITING_UNIT1("pdf.inOutInventory.table.output.sales.waiting.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_WAITING_UNIT2("pdf.inOutInventory.table.output.sales.waiting.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_TOTAL_UNIT1("pdf.inOutInventory.table.output.sales.total.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_TOTAL_UNIT2("pdf.inOutInventory.table.output.sales.total.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_QTY_UNIT1("pdf.inOutInventory.table.output.sales.returnSupplier.qty.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_QTY_UNIT2("pdf.inOutInventory.table.output.sales.returnSupplier.qty.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_PROMOTION_UNIT1(
        "pdf.inOutInventory.table.output.sales.returnSupplier.promotion.unit1"
    ),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_PROMOTION_UNIT2(
        "pdf.inOutInventory.table.output.sales.returnSupplier.promotion.unit2"
    ),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_TOTAL_UNIT1("pdf.inOutInventory.table.output.sales.returnSupplier.total.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SALES_RETURN_SUPPLIER_TOTAL_UNIT2("pdf.inOutInventory.table.output.sales.returnSupplier.total.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_OTHER_UNIT1("pdf.inOutInventory.table.output.otherOutput.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_OTHER_UNIT2("pdf.inOutInventory.table.output.otherOutput.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_DECREASE_UNIT1("pdf.inOutInventory.table.output.decrease.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_DECREASE_UNIT2("pdf.inOutInventory.table.output.decrease.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_VANSALES_UNIT1("pdf.inOutInventory.table.output.vanSalesOutput.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_VANSALES_UNIT2("pdf.inOutInventory.table.output.vanSalesOutput.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_SAMPLING_UNIT1("pdf.inOutInventory.table.output.samplingOutput.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_SAMPLING_UNIT2("pdf.inOutInventory.table.output.samplingOutput.unit2"),
    INVENTORY_IN_OUT_DETAIL_OUT_TOTAL_UNIT1("pdf.inOutInventory.table.output.total.unit1"),
    INVENTORY_IN_OUT_DETAIL_OUT_TOTAL_UNIT2("pdf.inOutInventory.table.output.total.unit2"),
    INVENTORY_IN_OUT_DETAIL_STOCK_AVAILABLE_UNIT1("pdf.inOutInventory.table.stockAvailable.unit1"),
    INVENTORY_IN_OUT_DETAIL_STOCK_AVAILABLE_UNIT2("pdf.inOutInventory.table.stockAvailable.unit2"),
    INVENTORY_IN_OUT_DETAIL_STOCK_AVAILABLE_VALUE("pdf.inOutInventory.table.stockAvailable.value"),
    INVENTORY_IN_OUT_DETAIL_NOT_IN_STOCK_UNIT1("pdf.inOutInventory.table.notInStock.unit1"),
    INVENTORY_IN_OUT_DETAIL_NOT_IN_STOCK_UNIT2("pdf.inOutInventory.table.notInStock.unit2"),
    INVENTORY_IN_OUT_DETAIL_NOT_IN_STOCK_VALUE("pdf.inOutInventory.table.notInStock.value"),
    INVENTORY_IN_OUT_DETAIL_EST_STOCK_UNIT1("pdf.inOutInventory.table.estStock.unit1"),
    INVENTORY_IN_OUT_DETAIL_EST_STOCK_UNIT2("pdf.inOutInventory.table.estStock.unit2"),
    INVENTORY_IN_OUT_DETAIL_EST_STOCK_VALUE("pdf.inOutInventory.table.estStock.value"),
    INVENTORY_IN_OUT_DETAIL_TOTAL("pdf.inOutInventory.table.total"),

    // Request Payment Distributor
    REQUEST_PAYMENT_TITLE("pdf.paymentRequest.title"),
    REQUEST_PAYMENT_REQUEST_USER("pdf.paymentRequest.requestUser"),
    REQUEST_PAYMENT_REQDEPT("pdf.paymentRequest.reqDept"),
    REQUEST_PAYMENT_USER_PHONE("pdf.paymentRequest.userPhone"),
    REQUEST_PAYMENT_FACTORY("pdf.paymentRequest.factory"),
    REQUEST_PAYMENT_RECEIVER("pdf.paymentRequest.receiver"),
    REQUEST_PAYMENT_CONTENT("pdf.paymentRequest.paymentContent"),
    REQUEST_PAYMENT_CENTER("pdf.paymentRequest.center"),
    REQUEST_PAYMENT_PROJECT("pdf.paymentRequest.project"),
    REQUEST_PAYMENT_CONTENT_DETAIL("pdf.paymentRequest.paymentContentDetail"),
    REQUEST_PAYMENT_TABLE_COL1("pdf.paymentRequest.table.col1"),

    REQUEST_PAYMENT_TABLE_COL2("pdf.paymentRequest.table.col2"),
    REQUEST_PAYMENT_TABLE_COL3("pdf.paymentRequest.table.col3"),
    REQUEST_PAYMENT_TABLE_COL4("pdf.paymentRequest.table.col4"),
    REQUEST_PAYMENT_TABLE_COL5("pdf.paymentRequest.table.col5"),
    REQUEST_PAYMENT_TABLE_COL6("pdf.paymentRequest.table.col6"),
    REQUEST_PAYMENT_TABLE_COL7("pdf.paymentRequest.table.col7"),
    REQUEST_PAYMENT_TABLE_COL8("pdf.paymentRequest.table.col8"),
    REQUEST_PAYMENT_TABLE_COL9("pdf.paymentRequest.table.col9"),
    REQUEST_PAYMENT_TABLE_TOTAL("pdf.paymentRequest.table.total"),
    REQUEST_PAYMENT_SIGNATURE_DATE("pdf.paymentRequest.signature.reqDate"),
    REQUEST_PAYMENT_SIGNATURE_USER("pdf.paymentRequest.signature.reqUser"),
    REQUEST_PAYMENT_SIGNATURE_DEPT("pdf.paymentRequest.signature.chiefOfDept"),
    REQUEST_PAYMENT_SIGNATURE_MANAGER("pdf.paymentRequest.signature.accountingManager"),
    REQUEST_PAYMENT_SIGNATURE_DIRECTOR("pdf.paymentRequest.signature.director"),
    REQUEST_PAYMENT_SIGNATURE_FULLNAME("pdf.paymentRequest.signature.signAndWriteFullName"),
    REQUEST_PAYMENT_CONTENT_TEXT("pdf.paymentRequest.paymentContentText"),
    REQUEST_PAYMENT_OFFICE("pdf.paymentRequest.office"),
    REQUEST_PAYMENT_PROJECT_OREX("pdf.paymentRequest.projectOrex"),
    REQUEST_PAYMENT_COST_CENTER("pdf.paymentRequest.costCenter"),

    // Delivery Note Billing
    DELIVERY_NOTE_BILLING_TITLE("pdf.deliveryNoteBilling.title"),
    DELIVERY_NOTE_BILLING_SIGNATURE_ACCOUNTING("pdf.deliveryNoteBilling.signature.accounting"),
    DELIVERY_NOTE_BILLING_SIGNATURE_DELIVERYMAN("pdf.deliveryNoteBilling.signature.deliveryman"),
    DELIVERY_NOTE_BILLING_SIGNATURE_CUSTOMER("pdf.deliveryNoteBilling.signature.customer"),
    DELIVERY_NOTE_BILLING_SIGNATURE_WRITE_FULLNAME("pdf.deliveryNoteBilling.signature.signAndWriteFullName"),
    DELIVERY_NOTE_BILLING_LUCKY_DRAW_REWARD("pdf.deliveryNoteBilling.luckyDrawReward"),

    DELIVERY_RETURN_AND_PAYMENT_TITLE("pdf.returnAndPayment.title"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_CUSTOMER("pdf.returnAndPayment.signature.customer"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_DELIVERYMAN("pdf.returnAndPayment.signature.deliveryman"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_OWNER("pdf.returnAndPayment.signature.owner"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_STOCKER("pdf.returnAndPayment.signature.stocker"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_ACCOUNTING("pdf.returnAndPayment.signature.accounting"),
    DELIVERY_RETURN_AND_PAYMENT_SIGNATURE_PRINT_DATE("pdf.returnAndPayment.signature.printDate"),

    // Exhibition Detail
    EXHIBITION_DETAIL_DISTRIBUTOR_NAME("pdf.exhibitionDetail.distributorName"),
    EXHIBITION_DETAIL_REGION_NAME("pdf.exhibitionDetail.regionName"),
    EXHIBITION_DETAIL_PRINT_DATE("pdf.exhibitionDetail.printDate"),
    EXHIBITION_DETAIL_TITLE("pdf.exhibitionDetail.title"),
    EXHIBITION_DETAIL_FROM_DATE("pdf.exhibitionDetail.fromDate"),
    EXHIBITION_DETAIL_TO_DATE("pdf.exhibitionDetail.toDate"),
    EXHIBITION_DETAIL_DESCRIPTION("pdf.exhibitionDetail.description"),
    EXHIBITION_DETAIL_TABLE_COL2("pdf.exhibitionDetail.table.col2"),
    EXHIBITION_DETAIL_TABLE_COL3("pdf.exhibitionDetail.table.col3"),
    EXHIBITION_DETAIL_TABLE_COL4("pdf.exhibitionDetail.table.col4"),
    EXHIBITION_DETAIL_TABLE_COL5("pdf.exhibitionDetail.table.col5"),
    EXHIBITION_DETAIL_TABLE_COL6("pdf.exhibitionDetail.table.col6"),
    EXHIBITION_DETAIL_TABLE_COL7("pdf.exhibitionDetail.table.col7"),
    EXHIBITION_DETAIL_TABLE_COL12("pdf.exhibitionDetail.table.col12"),
    EXHIBITION_DETAIL_TABLE_COL8("pdf.exhibitionDetail.table.col8"),
    EXHIBITION_DETAIL_TABLE_COL9("pdf.exhibitionDetail.table.col9"),
    EXHIBITION_DETAIL_TABLE_COL9_1("pdf.exhibitionDetail.table.col9_1"),
    EXHIBITION_DETAIL_TABLE_COL9_1_1("pdf.exhibitionDetail.table.col9_1_1"),
    EXHIBITION_DETAIL_TABLE_COL10("pdf.exhibitionDetail.table.col10"),
    EXHIBITION_DETAIL_TABLE_COL11("pdf.exhibitionDetail.table.col11"),
    EXHIBITION_DETAIL_TABLE_TOTAL("pdf.exhibitionDetail.table.total"),
    EXHIBITION_DETAIL_SIGNATURE_DATE("pdf.exhibitionDetail.signature.date"),
    EXHIBITION_DETAIL_SIGNATURE_DISTRIBUTOR("pdf.exhibitionDetail.signature.distributor"),
    EXHIBITION_DETAIL_SIGNATURE_USM("pdf.exhibitionDetail.signature.usm"),
    EXHIBITION_DETAIL_SIGNATURE_SIGNANDWRITEFULLNAME("pdf.exhibitionDetail.signature.signAndWriteFullName"),

    // Commercial Support
    COMMERCIAL_SUPPORT_PRINT_DATE("pdf.commercialSupport.printDate"),
    COMMERCIAL_SUPPORT_TITLE("pdf.commercialSupport.title"),
    COMMERCIAL_SUPPORT_DATE("pdf.commercialSupport.date"),
    COMMERCIAL_SUPPORT_DISTRIBUTOR("pdf.commercialSupport.distributor"),
    COMMERCIAL_SUPPORT_BUSINESS_TYPE("pdf.commercialSupport.businessType"),
    COMMERCIAL_SUPPORT_DISTRICT("pdf.commercialSupport.district"),
    COMMERCIAL_SUPPORT_USM("pdf.commercialSupport.usm"),
    COMMERCIAL_SUPPORT_TABLE_COL2("pdf.commercialSupport.table.col2"),
    COMMERCIAL_SUPPORT_TABLE_COL3("pdf.commercialSupport.table.col3"),
    COMMERCIAL_SUPPORT_TABLE_COL4("pdf.commercialSupport.table.col4"),
    COMMERCIAL_SUPPORT_TABLE_COL5("pdf.commercialSupport.table.col5"),
    COMMERCIAL_SUPPORT_TABLE_COL6("pdf.commercialSupport.table.col6"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL6_FROM_DATE("pdf.commercialSupport.table.subCol6.fromDate"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL6_TO_DATE("pdf.commercialSupport.table.subCol6.toDate"),
    COMMERCIAL_SUPPORT_TABLE_COL7("pdf.commercialSupport.table.col7"),
    COMMERCIAL_SUPPORT_TABLE_COL8("pdf.commercialSupport.table.col8"),
    COMMERCIAL_SUPPORT_TABLE_COL9("pdf.commercialSupport.table.col9"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL9_1("pdf.commercialSupport.table.subCol9.1"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL9_2("pdf.commercialSupport.table.subCol9.2"),

    COMMERCIAL_SUPPORT_TABLE_COL10("pdf.commercialSupport.table.col10"),
    COMMERCIAL_SUPPORT_TABLE_COL11("pdf.commercialSupport.table.col11"),
    COMMERCIAL_SUPPORT_TABLE_COL12("pdf.commercialSupport.table.col12"),
    COMMERCIAL_SUPPORT_TABLE_COL13("pdf.commercialSupport.table.col13"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL13_1("pdf.commercialSupport.table.subCol13.1"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL13_2("pdf.commercialSupport.table.subCol13.2"),
    COMMERCIAL_SUPPORT_TABLE_SUB_COL13_3("pdf.commercialSupport.table.subCol13.3"),
    COMMERCIAL_SUPPORT_TABLE_COL14("pdf.commercialSupport.table.col14"),
    COMMERCIAL_SUPPORT_TABLE_COL15("pdf.commercialSupport.table.col15"),
    COMMERCIAL_SUPPORT_TABLE_COL16("pdf.commercialSupport.table.col16"),

    COMMERCIAL_SUPPORT_OWNER_DISTRIBUTOR("pdf.commercialSupport.ownerDistributor"),
    COMMERCIAL_SUPPORT_OWNER_WIRITE_FULLNAME("pdf.commercialSupport.writeAndFullName"),
    COMMERCIAL_SUPPORT_SIGNATURE("pdf.commercialSupport.signature"),
    COMMERCIAL_SUPPORT_MANAGER_REGION("pdf.commercialSupport.managerRegion"),

    // loyalty final settlement
    LOYALTY_FINAL_SETTLEMENT_DISTRIBUTOR_NAME("pdf.loyaltyFinalSettlement.distributorName"),
    LOYALTY_FINAL_SETTLEMENT_PROVINCE_NAME("pdf.loyaltyFinalSettlement.provinceName"),
    LOYALTY_FINAL_SETTLEMENT_USM("pdf.loyaltyFinalSettlement.usm"),
    LOYALTY_FINAL_SETTLEMENT_LOYALTY_NAME("pdf.loyaltyFinalSettlement.loyaltyName"),
    LOYALTY_FINAL_SETTLEMENT_LOYALTY_FORM("pdf.loyaltyFinalSettlement.loyaltyForm"),
    LOYALTY_FINAL_SETTLEMENT_LOYALTY_DESCRIPTION("pdf.loyaltyFinalSettlement.loyaltyDescription"),
    LOYALTY_FINAL_SETTLEMENT_PRINT_DATE("pdf.loyaltyFinalSettlement.printDate"),
    LOYALTY_FINAL_SETTLEMENT_TITLE("pdf.loyaltyFinalSettlement.title"),
    LOYALTY_FINAL_SETTLEMENT_FROM_DATE("pdf.loyaltyFinalSettlement.fromDate"),
    LOYALTY_FINAL_SETTLEMENT_TO_DATE("pdf.loyaltyFinalSettlement.toDate"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL2("pdf.loyaltyFinalSettlement.table.col2"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL3("pdf.loyaltyFinalSettlement.table.col3"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL4("pdf.loyaltyFinalSettlement.table.col4"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL5("pdf.loyaltyFinalSettlement.table.col5"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL6("pdf.loyaltyFinalSettlement.table.col6"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL7("pdf.loyaltyFinalSettlement.table.col7"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL8("pdf.loyaltyFinalSettlement.table.col8"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL9("pdf.loyaltyFinalSettlement.table.col9"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL10("pdf.loyaltyFinalSettlement.table.col10"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL11("pdf.loyaltyFinalSettlement.table.col11"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL12("pdf.loyaltyFinalSettlement.table.col12"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL13("pdf.loyaltyFinalSettlement.table.col13"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL14("pdf.loyaltyFinalSettlement.table.col14"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL14_1("pdf.loyaltyFinalSettlement.table.col14_1"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL14_2("pdf.loyaltyFinalSettlement.table.col14_2"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL14_3("pdf.loyaltyFinalSettlement.table.col14_3"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL15("pdf.loyaltyFinalSettlement.table.col15"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL16("pdf.loyaltyFinalSettlement.table.col16"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL17("pdf.loyaltyFinalSettlement.table.col17"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_COL18("pdf.loyaltyFinalSettlement.table.col18"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_TOTAL("pdf.loyaltyFinalSettlement.table.total"),
    LOYALTY_FINAL_SETTLEMENT_SIGNATURE_DATE("pdf.loyaltyFinalSettlement.signature.date"),
    LOYALTY_FINAL_SETTLEMENT_SIGNATURE_DISTRIBUTOR("pdf.loyaltyFinalSettlement.signature.distributor"),
    LOYALTY_FINAL_SETTLEMENT_SIGNATURE_USM("pdf.loyaltyFinalSettlement.signature.usm"),
    LOYALTY_FINAL_SETTLEMENT_SIGNATURE_WRITE_FULLNAME("pdf.loyaltyFinalSettlement.signature.signAndWriteFullName"),
    LOYALTY_FINAL_SETTLEMENT_TABLE_ALL_VALUE("pdf.loyaltyFinalSettlement.table.all"),

    // loyalty payment progress
    LOYALTY_PAYMENT_PROGRESS_DISTRIBUTOR_NAME("pdf.loyaltyPaymentProgress.distributorName"),
    LOYALTY_PAYMENT_PROGRESS_PROVINCE_NAME("pdf.loyaltyPaymentProgress.provinceName"),
    LOYALTY_PAYMENT_PROGRESS_USM("pdf.loyaltyPaymentProgress.usm"),
    LOYALTY_PAYMENT_PROGRESS_LOYALTY_NAME("pdf.loyaltyPaymentProgress.loyaltyName"),
    LOYALTY_PAYMENT_PROGRESS_LOYALTY_FORM("pdf.loyaltyPaymentProgress.loyaltyForm"),
    LOYALTY_PAYMENT_PROGRESS_LOYALTY_DESCRIPTION("pdf.loyaltyPaymentProgress.loyaltyDescription"),
    LOYALTY_PAYMENT_PROGRESS_PRINT_DATE("pdf.loyaltyPaymentProgress.printDate"),
    LOYALTY_PAYMENT_PROGRESS_TITLE("pdf.loyaltyPaymentProgress.title"),
    LOYALTY_PAYMENT_PROGRESS_FROM_DATE("pdf.loyaltyPaymentProgress.fromDate"),
    LOYALTY_PAYMENT_PROGRESS_TO_DATE("pdf.loyaltyPaymentProgress.toDate"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL2("pdf.loyaltyPaymentProgress.table.col2"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL3("pdf.loyaltyPaymentProgress.table.col3"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL4("pdf.loyaltyPaymentProgress.table.col4"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL5("pdf.loyaltyPaymentProgress.table.col5"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL6("pdf.loyaltyPaymentProgress.table.col6"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL7("pdf.loyaltyPaymentProgress.table.col7"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL8("pdf.loyaltyPaymentProgress.table.col8"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL9("pdf.loyaltyPaymentProgress.table.col9"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL10("pdf.loyaltyPaymentProgress.table.col10"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL11("pdf.loyaltyPaymentProgress.table.col11"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL12("pdf.loyaltyPaymentProgress.table.col12"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL13("pdf.loyaltyPaymentProgress.table.col13"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL14("pdf.loyaltyPaymentProgress.table.col14"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL14_1("pdf.loyaltyPaymentProgress.table.col14_1"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL14_2("pdf.loyaltyPaymentProgress.table.col14_2"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL14_3("pdf.loyaltyPaymentProgress.table.col14_3"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL15("pdf.loyaltyPaymentProgress.table.col15"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL16("pdf.loyaltyPaymentProgress.table.col16"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL17("pdf.loyaltyPaymentProgress.table.col17"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL18("pdf.loyaltyPaymentProgress.table.col18"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_COL19("pdf.loyaltyPaymentProgress.table.col19"),
    LOYALTY_PAYMENT_PROGRESS_TABLE_TOTAL("pdf.loyaltyPaymentProgress.table.total"),
    LOYALTY_PAYMENT_PROGRESS_SIGNATURE_DATE("pdf.loyaltyPaymentProgress.signature.date"),
    LOYALTY_PAYMENT_PROGRESS_SIGNATURE_DISTRIBUTOR("pdf.loyaltyPaymentProgress.signature.distributor"),
    LOYALTY_PAYMENT_PROGRESS_SIGNATURE_USM("pdf.loyaltyPaymentProgress.signature.usm"),
    LOYALTY_PAYMENT_PROGRESS_SIGNATURE_WRITE_FULLNAME("pdf.loyaltyPaymentProgress.signature.signAndWriteFullName"),

    // ProductPurchase Invoice
    PRODUCT_PURCHASE_INVOICE_DATE_PRINT("pdf.productPurchaseInvoice.datePrint"),
    PRODUCT_PURCHASE_INVOICE_TITLE("pdf.productPurchaseInvoice.title"),
    PRODUCT_PURCHASE_INVOICE_FROM_DATE("pdf.productPurchaseInvoice.fromDate"),
    PRODUCT_PURCHASE_INVOICE_TO_DATE("pdf.productPurchaseInvoice.toDate"),
    PRODUCT_PURCHASE_INVOICE_VENDOR("pdf.productPurchaseInvoice.vendor"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL2("pdf.productPurchaseInvoice.table.col2"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL3("pdf.productPurchaseInvoice.table.col3"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL4("pdf.productPurchaseInvoice.table.col4"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL5("pdf.productPurchaseInvoice.table.col5"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL6("pdf.productPurchaseInvoice.table.col6"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL7("pdf.productPurchaseInvoice.table.col7"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL8("pdf.productPurchaseInvoice.table.col8"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL9("pdf.productPurchaseInvoice.table.col9"),
    PRODUCT_PURCHASE_INVOICE_TABLE_COL10("pdf.productPurchaseInvoice.table.col10"),
    PRODUCT_PURCHASE_INVOICE_TOTAL("pdf.productPurchaseInvoice.total"),

    // Distributor Program Settlement
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TITLE("pdf.distributorProgramSettlement.title"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_FROM_DATE("pdf.distributorProgramSettlement.fromDate"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TO_DATE("pdf.distributorProgramSettlement.toDate"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_COMPANY_NAME("pdf.distributorProgramSettlement.companyName"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_COMPANY_ADDRESS("pdf.distributorProgramSettlement.companyAddress"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_COMPANY_TAX_CODE("pdf.distributorProgramSettlement.companyTaxCode"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_DISTRIBUTOR_CODE("pdf.distributorProgramSettlement.distributorCode"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_DISTRIBUTOR_NAME("pdf.distributorProgramSettlement.distributorName"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_PRINT_DATE("pdf.distributorProgramSettlement.printDate"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL2("pdf.distributorProgramSettlement.table.col2"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL3("pdf.distributorProgramSettlement.table.col3"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL4("pdf.distributorProgramSettlement.table.col4"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL13("pdf.distributorProgramSettlement.table.col13"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL5("pdf.distributorProgramSettlement.table.col5"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL6("pdf.distributorProgramSettlement.table.col6"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL7("pdf.distributorProgramSettlement.table.col7"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL8("pdf.distributorProgramSettlement.table.col8"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL9("pdf.distributorProgramSettlement.table.col9"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL10("pdf.distributorProgramSettlement.table.col10"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL11("pdf.distributorProgramSettlement.table.col11"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL12("pdf.distributorProgramSettlement.table.col12"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL14("pdf.distributorProgramSettlement.table.col14"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL15("pdf.distributorProgramSettlement.table.col15"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_COL16("pdf.distributorProgramSettlement.table.col16"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_TOTAL("pdf.distributorProgramSettlement.table.total"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_TAX_PERCENT("pdf.distributorProgramSettlement.table.taxPercent"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_TAX_AMOUNT("pdf.distributorProgramSettlement.table.taxAmount"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_TOTAL_WITHOUT_TAX("pdf.distributorProgramSettlement.table.totalWithoutTax"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_SIGN_DISTRIBUTOR("pdf.distributorProgramSettlement.signature.distributor"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_SIGN_SALES_MANAGER("pdf.distributorProgramSettlement.signature.salesManager"),
    DISTRIBUTOR_PROGRAM_SETTLEMENT_TABLE_SIGN("pdf.distributorProgramSettlement.signature.sign"),

    // Program Settlement
    PROGRAM_SETTLEMENT_TITLE("pdf.programSettlement.title"),
    PROGRAM_SETTLEMENT_FROM_DATE("pdf.programSettlement.fromDate"),
    PROGRAM_SETTLEMENT_TO_DATE("pdf.programSettlement.toDate"),
    PROGRAM_SETTLEMENT_PRINT_DATE("pdf.programSettlement.printDate"),
    PROGRAM_SETTLEMENT_TABLE_COL2("pdf.programSettlement.table.col2"),
    PROGRAM_SETTLEMENT_TABLE_COL3("pdf.programSettlement.table.col3"),
    PROGRAM_SETTLEMENT_TABLE_COL4("pdf.programSettlement.table.col4"),
    PROGRAM_SETTLEMENT_TABLE_COL5("pdf.programSettlement.table.col5"),
    PROGRAM_SETTLEMENT_TABLE_COL6("pdf.programSettlement.table.col6"),
    PROGRAM_SETTLEMENT_TABLE_COL7("pdf.programSettlement.table.col7"),
    PROGRAM_SETTLEMENT_TABLE_COL16("pdf.programSettlement.table.col16"),
    PROGRAM_SETTLEMENT_TABLE_COL8("pdf.programSettlement.table.col8"),
    PROGRAM_SETTLEMENT_TABLE_COL9("pdf.programSettlement.table.col9"),
    PROGRAM_SETTLEMENT_TABLE_COL10("pdf.programSettlement.table.col10"),
    PROGRAM_SETTLEMENT_TABLE_COL11("pdf.programSettlement.table.col11"),
    PROGRAM_SETTLEMENT_TABLE_COL12("pdf.programSettlement.table.col12"),
    PROGRAM_SETTLEMENT_TABLE_COL13("pdf.programSettlement.table.col13"),
    PROGRAM_SETTLEMENT_TABLE_COL14("pdf.programSettlement.table.col14"),
    PROGRAM_SETTLEMENT_TABLE_COL15("pdf.programSettlement.table.col15"),
    PROGRAM_SETTLEMENT_TABLE_COL17("pdf.programSettlement.table.col17"),
    PROGRAM_SETTLEMENT_TABLE_COL18("pdf.programSettlement.table.col18"),
    PROGRAM_SETTLEMENT_TABLE_COL19("pdf.programSettlement.table.col19"),
    PROGRAM_SETTLEMENT_TABLE_COL20("pdf.programSettlement.table.col20"),
    PROGRAM_SETTLEMENT_TABLE_COL21("pdf.programSettlement.table.col21"),
    PROGRAM_SETTLEMENT_TABLE_COL22("pdf.programSettlement.table.col22"),
    PROGRAM_SETTLEMENT_TABLE_TOTAL_WITHOUT_TAX("pdf.programSettlement.table.totalWithoutTax"),
    PROGRAM_SETTLEMENT_TABLE_TAX_PERCENT("pdf.programSettlement.table.taxPercent"),
    PROGRAM_SETTLEMENT_TABLE_TAX_AMOUNT("pdf.programSettlement.table.taxAmount"),
    PROGRAM_SETTLEMENT_TABLE_TOTAL("pdf.programSettlement.table.total"),
    PROGRAM_SETTLEMENT_TABLE_SIGN_DISTRIBUTOR("pdf.programSettlement.signature.distributor"),
    PROGRAM_SETTLEMENT_TABLE_SIGN_SALES_MANAGER("pdf.programSettlement.signature.salesManager"),
    PROGRAM_SETTLEMENT_TABLE_SIGN("pdf.programSettlement.signature.sign"),
    PROGRAM_SETTLEMENT_STLMT_DESC_LABEL1("pdf.programSettlement.stlmtDesc.label1"),
    PROGRAM_SETTLEMENT_STLMT_DESC_LABEL2("pdf.programSettlement.stlmtDesc.label2"),

    // Settlement Invoice
    SETTLEMENT_INVOICE_TITLE("pdf.settlementInvoice.title"),
    SETTLEMENT_INVOICE_FROM_DATE("pdf.settlementInvoice.fromDate"),
    SETTLEMENT_INVOICE_TO_DATE("pdf.settlementInvoice.toDate"),
    SETTLEMENT_INVOICE_PRINT_DATE("pdf.settlementInvoice.printDate"),
    SETTLEMENT_INVOICE_TABLE_COL2("pdf.settlementInvoice.table.col2"),
    SETTLEMENT_INVOICE_TABLE_COL3("pdf.settlementInvoice.table.col3"),
    SETTLEMENT_INVOICE_TABLE_COL4("pdf.settlementInvoice.table.col4"),
    SETTLEMENT_INVOICE_TABLE_COL5("pdf.settlementInvoice.table.col5"),
    SETTLEMENT_INVOICE_TABLE_COL6("pdf.settlementInvoice.table.col6"),
    SETTLEMENT_INVOICE_TABLE_COL7("pdf.settlementInvoice.table.col7"),
    SETTLEMENT_INVOICE_TABLE_COL8("pdf.settlementInvoice.table.col8"),
    SETTLEMENT_INVOICE_TABLE_COL9("pdf.settlementInvoice.table.col9"),
    SETTLEMENT_INVOICE_TABLE_COL10("pdf.settlementInvoice.table.col10"),
    SETTLEMENT_INVOICE_TABLE_TOTAL("pdf.settlementInvoice.table.total"),

    // Customer Answer Al
    CUSTOMER_ANSWER_AL_TITLE("pdf.customerAnswerAl.title"),
    CUSTOMER_ANSWER_AL_FROM_DATE("pdf.customerAnswerAl.fromDate"),
    CUSTOMER_ANSWER_AL_TO_DATE("pdf.customerAnswerAl.toDate"),
    CUSTOMER_ANSWER_AL_TABLE_COL1("pdf.customerAnswerAl.table.col1"),
    CUSTOMER_ANSWER_AL_TABLE_COL2("pdf.customerAnswerAl.table.col2"),
    CUSTOMER_ANSWER_AL_TABLE_COL3("pdf.customerAnswerAl.table.col3"),
    CUSTOMER_ANSWER_AL_TABLE_COL4("pdf.customerAnswerAl.table.col4"),
    CUSTOMER_ANSWER_AL_TABLE_COL5("pdf.customerAnswerAl.table.col5"),
    CUSTOMER_ANSWER_AL_TABLE_COL6("pdf.customerAnswerAl.table.col6"),
    CUSTOMER_ANSWER_AL_TABLE_COL7("pdf.customerAnswerAl.table.col7"),
    CUSTOMER_ANSWER_AL_TABLE_COL8("pdf.customerAnswerAl.table.col8"),

    // Customer Answer
    CUSTOMER_ANSWER_TITLE("pdf.customerAnswer.title"),
    CUSTOMER_ANSWER_FROM_DATE("pdf.customerAnswer.fromDate"),
    CUSTOMER_ANSWER_TO_DATE("pdf.customerAnswer.toDate"),
    CUSTOMER_ANSWER_TABLE_COL1("pdf.customerAnswer.table.col1"),
    CUSTOMER_ANSWER_TABLE_COL2("pdf.customerAnswer.table.col2"),
    CUSTOMER_ANSWER_TABLE_COL3("pdf.customerAnswer.table.col3"),
    CUSTOMER_ANSWER_TABLE_COL4("pdf.customerAnswer.table.col4"),
    CUSTOMER_ANSWER_TABLE_COL5("pdf.customerAnswer.table.col5"),
    CUSTOMER_ANSWER_TABLE_COL6("pdf.customerAnswer.table.col6"),
    CUSTOMER_ANSWER_TABLE_COL7("pdf.customerAnswer.table.col7"),
    CUSTOMER_ANSWER_TABLE_COL8("pdf.customerAnswer.table.col8"),
    CUSTOMER_ANSWER_TABLE_COL9("pdf.customerAnswer.table.col9"),
    CUSTOMER_ANSWER_TABLE_COL10("pdf.customerAnswer.table.col10"),
    CUSTOMER_ANSWER_TABLE_COL11("pdf.customerAnswer.table.col11"),
    CUSTOMER_ANSWER_TABLE_COL12("pdf.customerAnswer.table.col12"),
    CUSTOMER_ANSWER_TABLE_COL13("pdf.customerAnswer.table.col13"),

    // Customer Loyalty - Al
    CUSTOMER_LOYALTY_AL_TITLE("pdf.customerLoyaltyAl.title"),
    CUSTOMER_LOYALTY_AL_LOYALTY_FROMDATE("pdf.customerLoyaltyAl.fromDate"),
    CUSTOMER_LOYALTY_AL_LOYALTY_TODATE("pdf.customerLoyaltyAl.toDate"),
    CUSTOMER_LOYALTY_AL_LOYALTY_CODE("pdf.customerLoyaltyAl.loyaltyCode"),
    CUSTOMER_LOYALTY_AL_LOYALTY_NAME("pdf.customerLoyaltyAl.loyaltyName"),
    CUSTOMER_LOYALTY_AL_TABLE_COL1("pdf.customerLoyaltyAl.table.col1"),
    CUSTOMER_LOYALTY_AL_TABLE_COL2("pdf.customerLoyaltyAl.table.col2"),
    CUSTOMER_LOYALTY_AL_TABLE_COL3("pdf.customerLoyaltyAl.table.col3"),
    CUSTOMER_LOYALTY_AL_TABLE_COL4("pdf.customerLoyaltyAl.table.col4"),
    CUSTOMER_LOYALTY_AL_TABLE_COL5("pdf.customerLoyaltyAl.table.col5"),
    CUSTOMER_LOYALTY_AL_TABLE_COL6("pdf.customerLoyaltyAl.table.col6"),
    CUSTOMER_LOYALTY_AL_TABLE_COL7("pdf.customerLoyaltyAl.table.col7"),
    CUSTOMER_LOYALTY_AL_TABLE_COL8("pdf.customerLoyaltyAl.table.col8"),
    CUSTOMER_LOYALTY_AL_TABLE_COL9("pdf.customerLoyaltyAl.table.col9"),

    // Customer Loyalty - Al
    CUSTOMER_LOYALTY_TITLE("pdf.customerLoyalty.title"),
    CUSTOMER_LOYALTY_LOYALTY_CODE("pdf.customerLoyalty.loyaltyCode"),
    CUSTOMER_LOYALTY_LOYALTY_NAME("pdf.customerLoyalty.loyaltyName"),
    CUSTOMER_LOYALTY_FROM_DATE("pdf.customerLoyalty.fromDate"),
    CUSTOMER_LOYALTY_TO_DATE("pdf.customerLoyalty.toDate"),

    CUSTOMER_LOYALTY_TABLE_COL1("pdf.customerLoyalty.table.col1"),
    CUSTOMER_LOYALTY_TABLE_COL2("pdf.customerLoyalty.table.col2"),
    CUSTOMER_LOYALTY_TABLE_COL3("pdf.customerLoyalty.table.col3"),
    CUSTOMER_LOYALTY_TABLE_COL4("pdf.customerLoyalty.table.col4"),
    CUSTOMER_LOYALTY_TABLE_COL5("pdf.customerLoyalty.table.col5"),
    CUSTOMER_LOYALTY_TABLE_COL6("pdf.customerLoyalty.table.col6"),
    CUSTOMER_LOYALTY_TABLE_COL7("pdf.customerLoyalty.table.col7"),
    CUSTOMER_LOYALTY_TABLE_COL8("pdf.customerLoyalty.table.col8"),
    CUSTOMER_LOYALTY_TABLE_COL9("pdf.customerLoyalty.table.col9"),
    CUSTOMER_LOYALTY_TABLE_COL10("pdf.customerLoyalty.table.col10"),
    CUSTOMER_LOYALTY_TABLE_COL11("pdf.customerLoyalty.table.col11"),
    CUSTOMER_LOYALTY_TABLE_COL12("pdf.customerLoyalty.table.col12"),
    CUSTOMER_LOYALTY_TABLE_COL13("pdf.customerLoyalty.table.col13"),
    CUSTOMER_LOYALTY_TABLE_COL14("pdf.customerLoyalty.table.col14"),
    CUSTOMER_LOYALTY_TABLE_COL15("pdf.customerLoyalty.table.col15"),
    CUSTOMER_LOYALTY_TABLE_COL16("pdf.customerLoyalty.table.col16"),

    // coaching for HO
    COACHING_HO_TITLE("pdf.coachingHo.title"),
    COACHING_HO_TABLE_COL1("pdf.coachingHo.table.col1"),
    COACHING_HO_TABLE_COL2("pdf.coachingHo.table.col2"),
    COACHING_HO_TABLE_COL3("pdf.coachingHo.table.col3"),
    COACHING_HO_TABLE_COL4("pdf.coachingHo.table.col4"),
    COACHING_HO_TABLE_COL5("pdf.coachingHo.table.col5"),
    COACHING_HO_TABLE_COL6("pdf.coachingHo.table.col6"),
    COACHING_HO_TABLE_COL7("pdf.coachingHo.table.col7"),
    COACHING_HO_TABLE_COL8("pdf.coachingHo.table.col8"),
    COACHING_HO_TABLE_COL9("pdf.coachingHo.table.col9"),
    COACHING_HO_TABLE_COL10("pdf.coachingHo.table.col10"),

    // Sales target
    SALES_TARGET_TITLE("pdf.salesTarget.title"),
    SALES_TARGET_BASELINE("pdf.salesTarget.baseline"),
    SALES_TARGET_SOLM("pdf.salesTarget.soLm"),
    SALES_TARGET_SILM("pdf.salesTarget.siLm"),
    SALES_TARGET_INVENTORY("pdf.salesTarget.inventory"),
    SALES_TARGET_SI_TARGET("pdf.salesTarget.siTarget"),
    SALES_TARGET_SO_TARGET_TH("pdf.salesTarget.soTargetTh"),
    SALES_TARGET_SO_TARGET_NGK("pdf.salesTarget.soTargetNgk"),

    // Sampling note delivery
    SAMPLING_NOTE_TITLE("pdf.samplingNote.title"),
    SAMPLING_NOTE_SAMPLING_DATE("pdf.samplingNote.samplingDate"),
    SAMPLING_NOTE_PRINT_DATE("pdf.samplingNote.printDate"),
    SAMPLING_NOTE_NVBH("pdf.samplingNote.nvbh"),
    SAMPLING_NOTE_SAMPLING_NOTE_CODE("pdf.samplingNote.samplingNoteCode"),
    SAMPLING_NOTE_TABLE_COL2("pdf.samplingNote.table.col2"),
    SAMPLING_NOTE_TABLE_COL3("pdf.samplingNote.table.col3"),
    SAMPLING_NOTE_TABLE_COL4("pdf.samplingNote.table.col4"),
    SAMPLING_NOTE_TABLE_COL5("pdf.samplingNote.table.col5"),
    SAMPLING_NOTE_TABLE_COL6("pdf.samplingNote.table.col6"),
    SAMPLING_NOTE_TABLE_COL7("pdf.samplingNote.table.col7"),
    SAMPLING_NOTE_TABLE_COL8("pdf.samplingNote.table.col8"),
    SAMPLING_NOTE_TABLE_COL9("pdf.samplingNote.table.col9"),
    SAMPLING_NOTE_TABLE_COL10("pdf.samplingNote.table.col10"),
    SAMPLING_NOTE_TABLE_COL11("pdf.samplingNote.table.col11"),
    SAMPLING_NOTE_TABLE_TOTAL("pdf.samplingNote.table.total"),
    SAMPLING_NOTE_TABLE_TOTAL_NET_AMOUNT("pdf.samplingNote.table.totalNetAmount"),
    SAMPLING_NOTE_TABLE_TOTAL_WEIGHT("pdf.samplingNote.table.totalWeight"),
    SAMPLING_NOTE_TABLE_SIGNATURE_ACCOUNT("pdf.samplingNote.signature.accountant"),
    SAMPLING_NOTE_TABLE_SIGNATURE_SALES_MAN("pdf.samplingNote.signature.salesman"),
    SAMPLING_NOTE_TABLE_SIGNATURE_WAREHOUSE_KEEPER("pdf.samplingNote.signature.warehouseKeeper"),
    SAMPLING_NOTE_TABLE_SIGNATURE_SAMPLING_CREATOR("pdf.samplingNote.signature.samplingCreator"),
    SAMPLING_NOTE_TABLE_SIGNATURE_SIGN("pdf.samplingNote.signature.sign"),

    // Sampling settlement
    SAMPLING_SETTLEMENT_TITLE("pdf.samplingSettlement.title"),
    SAMPLING_SETTLEMENT_DATE("pdf.samplingSettlement.settlementDate"),
    SAMPLING_SETTLEMENT_PRINT_DATE("pdf.samplingSettlement.printDate"),
    SAMPLING_SETTLEMENT_NVBH("pdf.samplingSettlement.nvbh"),
    SAMPLING_SETTLEMENT_CODE("pdf.samplingSettlement.settlementCode"),
    SAMPLING_SETTLEMENT_TABLE_COL2("pdf.samplingSettlement.table.col2"),
    SAMPLING_SETTLEMENT_TABLE_COL3("pdf.samplingSettlement.table.col3"),
    SAMPLING_SETTLEMENT_TABLE_COL4("pdf.samplingSettlement.table.col4"),
    SAMPLING_SETTLEMENT_TABLE_COL5("pdf.samplingSettlement.table.col5"),
    SAMPLING_SETTLEMENT_TABLE_COL6("pdf.samplingSettlement.table.col6"),
    SAMPLING_SETTLEMENT_TABLE_COL7("pdf.samplingSettlement.table.col7"),
    SAMPLING_SETTLEMENT_TABLE_COL8("pdf.samplingSettlement.table.col8"),
    SAMPLING_SETTLEMENT_TABLE_COL9("pdf.samplingSettlement.table.col9"),
    SAMPLING_SETTLEMENT_TABLE_COL10("pdf.samplingSettlement.table.col10"),
    SAMPLING_SETTLEMENT_TABLE_COL11("pdf.samplingSettlement.table.col11"),
    SAMPLING_SETTLEMENT_TABLE_COL12("pdf.samplingSettlement.table.col12"),
    SAMPLING_SETTLEMENT_TABLE_COL13("pdf.samplingSettlement.table.col13"),
    SAMPLING_SETTLEMENT_TABLE_COL14("pdf.samplingSettlement.table.col14"),
    SAMPLING_SETTLEMENT_TABLE_COL15("pdf.samplingSettlement.table.col15"),
    SAMPLING_SETTLEMENT_TABLE_COL16("pdf.samplingSettlement.table.col16"),
    SAMPLING_SETTLEMENT_TABLE_COL17("pdf.samplingSettlement.table.col17"),
    SAMPLING_SETTLEMENT_TABLE_TOTAL("pdf.samplingSettlement.table.total"),
    SAMPLING_SETTLEMENT_TABLE_TOTAL_NET_AMOUNT("pdf.samplingSettlement.table.totalNetAmount"),
    SAMPLING_SETTLEMENT_TABLE_TOTAL_WEIGHT("pdf.samplingSettlement.table.totalWeight"),

    SAMPLING_SETTLEMENT_TABLE_SIGNATURE_ACCOUNT("pdf.samplingSettlement.signature.accountant"),
    SAMPLING_SETTLEMENT_TABLE_SIGNATURE_SALES_MAN("pdf.samplingSettlement.signature.salesMan"),
    SAMPLING_SETTLEMENT_TABLE_SIGNATURE_WAREHOUSE_KEEPER("pdf.samplingSettlement.signature.warehouseKeeper"),
    SAMPLING_SETTLEMENT_TABLE_SIGNATURE_SAMPLING_CREATOR("pdf.samplingSettlement.signature.samplingCreator"),
    SAMPLING_SETTLEMENT_TABLE_SIGNATURE_SIGN("pdf.samplingSettlement.signature.sign"),

    // Sampling note delivery
    VANSALES_NOTE_TITLE("pdf.vansalesNote.title"),
    VANSALES_NOTE_VANSALES_DATE("pdf.vansalesNote.vansalesDate"),
    VANSALES_NOTE_PRINT_DATE("pdf.vansalesNote.printDate"),
    VANSALES_NOTE_NVBH("pdf.vansalesNote.nvbh"),
    VANSALES_NOTE_VANSALES_CODE("pdf.vansalesNote.vansalesCode"),
    VANSALES_NOTE_TABLE_COL2("pdf.vansalesNote.table.col2"),
    VANSALES_NOTE_TABLE_COL3("pdf.vansalesNote.table.col3"),
    VANSALES_NOTE_TABLE_COL4("pdf.vansalesNote.table.col4"),
    VANSALES_NOTE_TABLE_COL5("pdf.vansalesNote.table.col5"),
    VANSALES_NOTE_TABLE_COL6("pdf.vansalesNote.table.col6"),
    VANSALES_NOTE_TABLE_COL7("pdf.vansalesNote.table.col7"),
    VANSALES_NOTE_TABLE_COL8("pdf.vansalesNote.table.col8"),
    VANSALES_NOTE_TABLE_COL9("pdf.vansalesNote.table.col9"),
    VANSALES_NOTE_TABLE_COL10("pdf.vansalesNote.table.col10"),
    VANSALES_NOTE_TABLE_COL11("pdf.vansalesNote.table.col11"),
    VANSALES_NOTE_TABLE_TOTAL("pdf.vansalesNote.table.total"),
    VANSALES_NOTE_TABLE_TOTAL_NET_AMOUNT("pdf.vansalesNote.table.totalNetAmount"),
    VANSALES_NOTE_TABLE_TOTAL_WEIGHT("pdf.vansalesNote.table.totalWeight"),
    VANSALES_NOTE_TABLE_SIGNATURE_ACCOUNT("pdf.vansalesNote.signature.accountant"),
    VANSALES_NOTE_TABLE_SIGNATURE_SALES_MAN("pdf.vansalesNote.signature.salesman"),
    VANSALES_NOTE_TABLE_SIGNATURE_WAREHOUSE_KEEPER("pdf.vansalesNote.signature.warehouseKeeper"),
    VANSALES_NOTE_TABLE_SIGNATURE_SAMPLING_CREATOR("pdf.vansalesNote.signature.samplingCreator"),
    VANSALES_NOTE_TABLE_SIGNATURE_SIGN("pdf.vansalesNote.signature.sign"),

    // VanSales Settlement
    VANSALES_SETTLEMENT_TITLE("pdf.vansalesSettlement.title"),
    VANSALES_SETTLEMENT_DATE("pdf.vansalesSettlement.settlementDate"),
    VANSALES_SETTLEMENT_PRINT_DATE("pdf.vansalesSettlement.printDate"),
    VANSALES_SETTLEMENT_TRUCK("pdf.vansalesSettlement.truck"),
    VANSALES_SETTLEMENT_CODE("pdf.vansalesSettlement.settlementCode"),
    VANSALES_SETTLEMENT_TABLE_COL2("pdf.vansalesSettlement.table.col2"),
    VANSALES_SETTLEMENT_TABLE_COL3("pdf.vansalesSettlement.table.col3"),
    VANSALES_SETTLEMENT_TABLE_COL4("pdf.vansalesSettlement.table.col4"),
    VANSALES_SETTLEMENT_TABLE_COL5("pdf.vansalesSettlement.table.col5"),
    VANSALES_SETTLEMENT_TABLE_COL6("pdf.vansalesSettlement.table.col6"),
    VANSALES_SETTLEMENT_TABLE_COL7("pdf.vansalesSettlement.table.col7"),
    VANSALES_SETTLEMENT_TABLE_COL8("pdf.vansalesSettlement.table.col8"),
    VANSALES_SETTLEMENT_TABLE_COL9("pdf.vansalesSettlement.table.col9"),
    VANSALES_SETTLEMENT_TABLE_COL10("pdf.vansalesSettlement.table.col10"),
    VANSALES_SETTLEMENT_TABLE_COL11("pdf.vansalesSettlement.table.col11"),
    VANSALES_SETTLEMENT_TABLE_COL12("pdf.vansalesSettlement.table.col12"),
    VANSALES_SETTLEMENT_TABLE_COL13("pdf.vansalesSettlement.table.col13"),
    VANSALES_SETTLEMENT_TABLE_COL14("pdf.vansalesSettlement.table.col14"),
    VANSALES_SETTLEMENT_TABLE_COL15("pdf.vansalesSettlement.table.col15"),
    VANSALES_SETTLEMENT_TABLE_COL16("pdf.vansalesSettlement.table.col16"),
    VANSALES_SETTLEMENT_TABLE_COL17("pdf.vansalesSettlement.table.col17"),
    VANSALES_SETTLEMENT_TABLE_COL18("pdf.vansalesSettlement.table.col18"),
    VANSALES_SETTLEMENT_TABLE_COL19("pdf.vansalesSettlement.table.col19"),
    VANSALES_SETTLEMENT_TABLE_COL20("pdf.vansalesSettlement.table.col20"),
    VANSALES_SETTLEMENT_TABLE_TOTAL("pdf.vansalesSettlement.table.total"),
    VANSALES_SETTLEMENT_TOTAL_NET_AMOUNT("pdf.vansalesSettlement.totalNetAmount"),
    VANSALES_SETTLEMENT_DISCOUNT("pdf.vansalesSettlement.discount"),
    VANSALES_SETTLEMENT_PERSONAL_INCOME_TAX("pdf.vansalesSettlement.personalIncomeTax"),
    VANSALES_SETTLEMENT_TABLE2_COL2("pdf.vansalesSettlement.table2.col2"),
    VANSALES_SETTLEMENT_TABLE2_COL3("pdf.vansalesSettlement.table2.col3"),
    VANSALES_SETTLEMENT_TABLE2_COL4("pdf.vansalesSettlement.table2.col4"),
    VANSALES_SETTLEMENT_TABLE2_COL5("pdf.vansalesSettlement.table2.col5"),
    VANSALES_SETTLEMENT_TABLE2_COL6("pdf.vansalesSettlement.table2.col6"),
    VANSALES_SETTLEMENT_TABLE2_COL7("pdf.vansalesSettlement.table2.col7"),
    VANSALES_SETTLEMENT_TABLE2_TOTAL("pdf.vansalesSettlement.table2.total"),
    VANSALES_SETTLEMENT_TABLE_SIGNATURE_ACCOUNT("pdf.vansalesSettlement.signature.accountant"),
    VANSALES_SETTLEMENT_TABLE_SIGNATURE_SALES_MAN("pdf.vansalesSettlement.signature.salesman"),
    VANSALES_SETTLEMENT_TABLE_SIGNATURE_WAREHOUSE_KEEPER("pdf.vansalesSettlement.signature.warehouseKeeper"),
    VANSALES_SETTLEMENT_TABLE_SIGNATURE_SAMPLING_CREATOR("pdf.vansalesSettlement.signature.samplingCreator"),
    VANSALES_SETTLEMENT_TABLE_SIGNATURE_SIGN("pdf.vansalesSettlement.signature.sign"),

    // Customer answer tracking
    CUSTOMER_ANSWER_TRACKING_TITLE("pdf.customerAnswerTracking.title"),
    CUSTOMER_ANSWER_TRACKING_FROM_DATE("pdf.customerAnswerTracking.from"),
    CUSTOMER_ANSWER_TRACKING_TO_DATE("pdf.customerAnswerTracking.to"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL1("pdf.customerAnswerTracking.table.col1"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL2("pdf.customerAnswerTracking.table.col2"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL3("pdf.customerAnswerTracking.table.col3"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL4("pdf.customerAnswerTracking.table.col4"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL5("pdf.customerAnswerTracking.table.col5"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL6("pdf.customerAnswerTracking.table.col6"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL7("pdf.customerAnswerTracking.table.col7"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL8("pdf.customerAnswerTracking.table.col8"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL9("pdf.customerAnswerTracking.table.col9"),
    CUSTOMER_ANSWER_TRACKING_TABLE_COL10("pdf.customerAnswerTracking.table.col10"),

    // Sampling settlement distributor
    SAMPLING_DISTRIBUTOR_TITLE("pdf.samplingDistributor.title"),
    SAMPLING_DISTRIBUTOR_PRINT_DATE("pdf.samplingDistributor.printDate"),
    SAMPLING_DISTRIBUTOR_FROM_DATE("pdf.samplingDistributor.fromDate"),
    SAMPLING_DISTRIBUTOR_TO_DATE("pdf.samplingDistributor.toDate"),
    SAMPLING_DISTRIBUTOR_DISTRIBUTOR("pdf.samplingDistributor.distributor"),
    SAMPLING_DISTRIBUTOR_PROVINCE("pdf.samplingDistributor.province"),
    SAMPLING_DISTRIBUTOR_USM("pdf.samplingDistributor.usm"),
    SAMPLING_DISTRIBUTOR_BUSINESS_TYPE_NAME("pdf.samplingDistributor.businessTypeName"),
    SAMPLING_DISTRIBUTOR_TABLE_COL1("pdf.samplingDistributor.table.col1"),
    SAMPLING_DISTRIBUTOR_TABLE_COL2("pdf.samplingDistributor.table.col2"),
    SAMPLING_DISTRIBUTOR_TABLE_COL3("pdf.samplingDistributor.table.col3"),
    SAMPLING_DISTRIBUTOR_TABLE_COL4("pdf.samplingDistributor.table.col4"),
    SAMPLING_DISTRIBUTOR_TABLE_COL5("pdf.samplingDistributor.table.col5"),
    SAMPLING_DISTRIBUTOR_TABLE_COL6("pdf.samplingDistributor.table.col6"),
    SAMPLING_DISTRIBUTOR_TABLE_COL7("pdf.samplingDistributor.table.col7"),
    SAMPLING_DISTRIBUTOR_TABLE_COL8("pdf.samplingDistributor.table.col8"),
    SAMPLING_DISTRIBUTOR_TABLE_COL9("pdf.samplingDistributor.table.col9"),
    SAMPLING_DISTRIBUTOR_TABLE_COL10("pdf.samplingDistributor.table.col10"),
    SAMPLING_DISTRIBUTOR_TABLE_COL11("pdf.samplingDistributor.table.col11"),
    SAMPLING_DISTRIBUTOR_TABLE_COL12("pdf.samplingDistributor.table.col12"),
    SAMPLING_DISTRIBUTOR_TABLE_COL13("pdf.samplingDistributor.table.col13"),
    SAMPLING_DISTRIBUTOR_TABLE_COL14("pdf.samplingDistributor.table.col14"),
    SAMPLING_DISTRIBUTOR_TABLE_COL15("pdf.samplingDistributor.table.col15"),
    SAMPLING_DISTRIBUTOR_TABLE_TOTAL("pdf.samplingDistributor.table.total"),
    SAMPLING_DISTRIBUTOR_SIGNATURE_SIGN("pdf.samplingDistributor.signature.sign"),
    SAMPLING_DISTRIBUTOR_SIGNATURE_SIGN_DAY("pdf.samplingDistributor.signature.signDay"),
    SAMPLING_DISTRIBUTOR_SIGNATURE_DISTRIBUTOR("pdf.samplingDistributor.signature.distributor"),
    SAMPLING_DISTRIBUTOR_SIGNATURE_BUSINESS_MANAGEMENT("pdf.samplingDistributor.signature.businessManagement"),

    // Promotion cash
    PROMOTION_CASH_TITLE("pdf.promotionCash.title"),
    PROMOTION_CASH_FROM_DATE("pdf.promotionCash.fromDate"),
    PROMOTION_CASH_TO_DATE("pdf.promotionCash.toDate"),
    PROMOTION_CASH_TABLE_COL1("pdf.promotionCash.table.col1"),
    PROMOTION_CASH_TABLE_COL2("pdf.promotionCash.table.col2"),
    PROMOTION_CASH_TABLE_COL3("pdf.promotionCash.table.col3"),
    PROMOTION_CASH_TABLE_COL4("pdf.promotionCash.table.col4"),
    PROMOTION_CASH_TABLE_COL5("pdf.promotionCash.table.col5"),
    PROMOTION_CASH_TABLE_COL6("pdf.promotionCash.table.col6"),
    PROMOTION_CASH_TABLE_COL7("pdf.promotionCash.table.col7"),

    // PartnerProduct Region
    MATERIAL_GROUP_REGION_NOT_SETUP("error.materialRegion.materialGroupNotSetup"),

    // Email
    // Purchase Invoice
    EMAIL_PURCHASE_INVOICE("email.purchaseInvoice.subject"),
    EMAIL_PURCHASE_DETAIL("email.purchaseDetail.subject"),
    EMAIL_PURCHASE_INVOICE_RECORED("email.purchaseInvoiceRecorded.subject"),

    // VISIT PLAN
    EMAIL_VISIT_PLAN_UPDATE_MCP_NOTIFY_SC("email.visitPlanUpdateMcp.notifyToSc.subject"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_NOTIFY_SC_WELCOME("email.visitPlanUpdateMcp.notifyToSc.welcome"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_NOTIFY_SC_WELCOME_CONTENT("email.visitPlanUpdateMcp.notifyToSc.welcome.content"),

    EMAIL_VISIT_PLAN_UPDATE_MCP_APPROVE("email.visitPlanUpdateMcp.approve.subject"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_APPROVE_WELCOME("email.visitPlanUpdateMcp.approve.welcome"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_APPROVE_WELCOME_CONTENT("email.visitPlanUpdateMcp.approve.welcome.content"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_REJECT("email.visitPlanUpdateMcp.reject.subject"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_REJECT_WELCOME("email.visitPlanUpdateMcp.reject.welcome"),
    EMAIL_VISIT_PLAN_UPDATE_MCP_REJECT_WELCOME_CONTENT("email.visitPlanUpdateMcp.reject.welcome.content"),

    // Email Settlement
    EMAIL_PROGRAM_SUBJECT("email.programWarningOpen.subject"),

    // Email De-actived Sales Man Without Route
    EMAIL_SM_DEACTIVATED_WITHOUT_ROUTE("email.deActivedSalesManWithoutRoute.subject"),

    // Email De Actived customer without sales out
    EMAIL_CUSTOMER_DEACTIVATED_WITHOUT_SALES_OUT("email.deActivedCustomerWithoutSalesOut.subject"),

    // Email Sales Force
    EMAIL_SALES_FORCE("email.salesForce.subject"),

    // Email Notify to admin about distributor integrate SAP
    EMAIL_DISTRIBUTOR_INTEGRATE_SAP("email.distributorIntegrateSap.subject"),

    // Email report customer answer ai
    EMAIL_CUSTOMER_ANSWER_AI_GROUP_BY_CUSTOMER("email.customerAnswerAI.groupByCustomer.subject"),

    EMAIL_REMIND_PURCHASE_INVOICE_NOT_RECORDED("email.remindPurchaseInvoiceNotRecorded.subject"),

    // Program Settlement
    PROGRAM_STLMT_NO_DATA("error.programSettlement.noData"),
    PROGRAM_STLMT_INVOICE_INVALID("error.programSettlementDetail.invoiceInvalid"),
    STLMT_DETAIL_INVOICE_DATE_INVALID("error.programSettlementDetail.invoiceDateInvalid"),
    //STLMT_SAMPLING_PRODUCT_QTY_INVALID("error.programSettlementSampling.productQtyInvalid"),
    PROGRAM_STLMT_INVOICE_PAID("error.programSettlement.invoicePaid"),

    // Expense
    EXPENSE_LIMIT_AMOUNT("expense.limit.amount"),
    EXPENSE_LIMIT_TIME("expense.limit.time"),
    ERROR_INVOICE_USED("error.expense.invoice.used"),
    ERROR_TOTAL_NIGHTS("error.expense.totalNights"),
    ERROR_MIN_DAYS("error.expense.minDays"),
    ERROR_STAY_DISTANCE("error.expense.stay.distance"),

    // Report coaching
    COACHING_TITLE("pdf.coaching.title"),
    COACHING_USM("pdf.coaching.usm"),
    COACHING_NPP("pdf.coaching.npp"),
    COACHING_TOTAL_STAYED("pdf.coaching.totalStayed"),
    COACHING_CALENDAR_TIME("pdf.coaching.calendar.time"),
    COACHING_CALENDAR_D1("pdf.coaching.calendar.d1"),
    COACHING_CALENDAR_D2("pdf.coaching.calendar.d2"),
    COACHING_CALENDAR_D3("pdf.coaching.calendar.d3"),
    COACHING_CALENDAR_D4("pdf.coaching.calendar.d4"),
    COACHING_CALENDAR_D5("pdf.coaching.calendar.d5"),
    COACHING_CALENDAR_D6("pdf.coaching.calendar.d6"),
    COACHING_CALENDAR_D7("pdf.coaching.calendar.d7"),
    COACHING_CALENDAR_WEEK("pdf.coaching.calendar.week"),
    COACHING_CALENDAR_DISTRIBUTOR_NAME("pdf.coaching.calendar.distributorName"),
    COACHING_CALENDAR_DESCRIPTION("pdf.coaching.calendar.description"),
    COACHING_CALENDAR_WORK_ADDRESS("pdf.coaching.calendar.workAddress"),
    COACHING_CALENDAR_DISTANCE("pdf.coaching.calendar.distance"),
    COACHING_CALENDAR_STAY("pdf.coaching.calendar.stay"),
    COACHING_CALENDAR_STAY_GPS("pdf.coaching.calendar.stayGps"),
    COACHING_SIGNATURE_APPROVAL("pdf.coaching.signature.approval"),
    COACHING_SIGNATURE_DIRECT_SUPERVISOR("pdf.coaching.signature.directSupervisor"),
    COACHING_SIGNATURE_DATE("pdf.coaching.signature.date"),
    COACHING_SIGNATURE_CREATE_BY("pdf.coaching.signature.createBy"),

    // Fw note

    FIELDWORK_NOTE_INFO("pdf.fwNote.info"),
    FIELDWORK_NOTE_IMAGE("pdf.fwNote.image"),
    FIELDWORK_NOTE_DISTRIBUTOR("pdf.fwNote.distributor"),
    FIELDWORK_NOTE_TIME_VISIT("pdf.fwNote.timeVisit"),
    FIELDWORK_NOTE_CUSTOMER("pdf.fwNote.customer"),
    FIELDWORK_NOTE_NVBH("pdf.fwNote.nvbh"),
    FIELDWORK_NOTE_WEEK("pdf.fwNote.week"),
    FIELDWORK_NOTE_LAST_VISIT("pdf.fwNote.lastVisit"),
    FIELDWORK_NOTE_LAST_ORDER("pdf.fwNote.lastOrder"),

    // DNTT
    USER_CLAIM_RESULT_TITLE("pdf.userClaimResult.title"),
    USER_CLAIM_RESULT_TABLE_COL2("pdf.userClaimResult.table.col2"),
    USER_CLAIM_RESULT_TABLE_COL3("pdf.userClaimResult.table.col3"),
    USER_CLAIM_RESULT_TABLE_COL4("pdf.userClaimResult.table.col4"),
    USER_CLAIM_RESULT_TABLE_COL5("pdf.userClaimResult.table.col5"),
    USER_CLAIM_RESULT_TABLE_COL6("pdf.userClaimResult.table.col6"),
    USER_CLAIM_RESULT_TABLE_COL7("pdf.userClaimResult.table.col7"),
    USER_CLAIM_RESULT_TABLE_COL8("pdf.userClaimResult.table.col8"),
    USER_CLAIM_RESULT_TABLE_FOOTER("pdf.userClaimResult.table.footer"),
    USER_CLAIM_RESULT_CASH_BY_WORD("pdf.userClaimResult.cashByWord"),
    USER_CLAIM_RESULT_BANK1("pdf.userClaimResult.bank1"),
    USER_CLAIM_RESULT_BANK2("pdf.userClaimResult.bank2"),
    USER_CLAIM_RESULT_COMPANY_PAID("pdf.userClaimResult.companyPaid"),
    USER_CLAIM_RESULT_ACCOUNTANT_PAID("pdf.userClaimResult.accountantPaid"),
    USER_CLAIM_RESULT_ACCOUNTANT1("pdf.userClaimResult.accountant1"),
    USER_CLAIM_RESULT_ACCOUNTANT2("pdf.userClaimResult.accountant2"),
    USER_CLAIM_RESULT_CEO("pdf.userClaimResult.ceo"),
    USER_CLAIM_RESULT_RECORDED_DATE("pdf.userClaimResult.recordedDate");

    /**
     * The message id.
     */
    private final String messageId;

    MessageKeys(String messageId) {
        this.messageId = messageId;
    }

    public String getValue() {
        return messageId;
    }
}
